### ISSUE TITLE
 enum SIPResponseStatusCodesEnum need changed

### ISSUE THREAD

**Issue by dongzhisong** [sipsorcery/sipsorcery#127]
hi,in the enum SIPResponseStatusCodesEnum, for 401 Unauthorised i think it need to be changed  from Unauthorised to Unauthorized.

**Comment by apdevelop** [comment]
Moreover, the enum should be better named `SIPResponseStatusCode`. Compare it with `System.Net.HttpStatusCode`.
[Naming Enumerations
](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces?redirectedfrom=MSDN)
> ✓ DO use a singular type name for an enumeration unless its values are bit fields.
> X DO NOT use an "Enum" suffix in enum type names.

Such renaming will be breaking change, though.

**Comment by apdevelop** [comment]
> Equivalent to HTTP status 401. System.Net.HttpStatusCode.Unauthorized

[Authorise vs. authorize](https://grammarist.com/spelling/authorise-authorize/)
> For the verb meaning to grant authority or to give permission, authorize is the standard spelling in American and Canadian English. Authorise is standard in all main varieties of English outside North America.

**Comment by sipsorcery** [comment]
I'm from outside North America and I always deliberately use `s` in words like `authorise`. It doesn't make any difference far as the `SIPResponseStatusCodesEnum` goes. It's clear what the word means with either spelling.

In cases where it does matter such as `SIP_HEADER_AUTHORIZATION` and `SIP_HEADER_PROXYAUTHORIZATION` the `z` spelling is used.

As far as the .Net naming guidelines go you'll notice that they were published in 2008. A lot of the core classes in this library were written in 2005 and 2006. The main guideline I wish had been around at the the time was Pascal case on 3 letter acronyms, `SipRequest` instead of `SIPRequest` etc. I do recall deliberating over it at the time and made the decision based on most of the code samples I came across from the C & C++ Worlds.

At this point int time tt's not justified to make a wholesale change for guidelines. It's also important to keep the style consistent across old and new code as much as possible. It makes the code easier to read and grasp.
