### ISSUE TITLE
class NetServices obsoletes LocalIPConfig?

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#128]
Hey Aaron,
I don't see any meaningful difference between methods in SIPSorcery.Sys.NetServices and SIPSorcery.Sys.LocalIPConfig.
As far as I see "GetLocalIPv4Addresses" is the only used method in LocalIPConfig and can be easily replaced by NetServices.GetAllLocalIPAddresses, but I do not know if ParseIPSockets is used somewhere.
If class LocalIPConfig is used somewhere, there should be additional methods and usage for Local/Default IPv6-Addresses (just for completion).

Ralf

**Comment by sipsorcery** [comment]
Hi Raif,
The `LocalIPConfig` class is probably completely redundant and cane be removed unless you see something there worth keeping?

The `GetDefault*Address` methods don't work properly because there isn't such a thing as a default address. At the time the idea was the the default address was the one used for iternet comms and should act as a fallback if prefix/mask matching didn't work. It was a fragile and error prone way to choose the correct local IP address.

The reliable way is to use the `NetServices.GetLocalAddress*` methods which use a trick of calling bind on a UDP socket to interrogate the operating system's routing table. I'd never come across that trick until a few weeks ago. You can read all about it [here](https://github.com/sipsorcery/sipsorcery/issues/97) if you're interested.

**Comment by rj2Skipper** [comment]
I don't see any benefit in keeping LocalIPConfig

Ralf

**Comment by sipsorcery** [comment]
Removed `LocalIPConfig` class.
