### ISSUE TITLE
TAP Task Asynchronous Programming (async/await)

### ISSUE THREAD

**Issue by Yitzchok** [sipsorcery/sipsorcery#137]
It seems like currently, this project consists of both synchronous and asynchronous methods in a non-consistant way. Also, there is synchronous code that call asynchronous code, which is known in .NET to cause issues in a few ways while also not really providing the benefits of using asynchronous code.

As a library, there are certain things that must be done in order to avoid deadlocks in projects that use this library which includes calling *Async(...).**ConfigureAway(false) every single time** we await a Task.

https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-

https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

**Comment by sipsorcery** [comment]
The .NET Framework [Socket](https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,c84007a498b38b5f) class supplies both synchronous and async methods, `Send`, `Receive`, `SendAsync`, `ReceiveAsync` etc. Admittedly there's no async/await TAP in that class.

Actually [TcpClient](https://referencesource.microsoft.com/#System/net/System/Net/Sockets/TCPClient.cs,943f9db3a7511918) looks closer to this library. Interestingly there's no async/await there either. it does it the opposite way. everything is synchronous and to make them async uses an event callback.

**Comment by Yitzchok** [comment]
They are going from [Asynchronous Programming Model (APM)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/asynchronous-programming-model-apm) to [Task Parallel Library (TPL)
](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl)

**Comment by Yitzchok** [comment]
https://github.com/microsoft/vs-threading/blob/master/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse

Some other good info on using async/await.

https://devblogs.microsoft.com/pfxteam/asyncawait-faq/

https://docs.microsoft.com/en-us/archive/msdn-magazine/2011/october/asynchronous-programming-async-performance-understanding-the-costs-of-async-and-await

https://www.anthonysteele.co.uk/AsyncBasicMistakes

https://devblogs.microsoft.com/dotnet/configureawait-faq/

https://github.com/gitextensions/gitextensions/wiki/Async-guidelines

**Comment by sipsorcery** [comment]
Relevant https://github.com/dotnet/corefx/issues/25154#issuecomment-566683020.

Point being that getting a TPL interface right is not easy, If corefx (who are likely to have access to the people that designed the pattern) find it challenging then it can be assumed it takes a substantial amount of effort.

I've never really found the lack of documentation to be the problem, almost the opposite.

IMHO I'm still inclined towards TPM as the best available approach for the application using this library, especially when that application is a GUI. It's a big chunk of extra work to convert the current classes but it's now on the list.

**Comment by Yitzchok** [comment]
TPM? Do you mean TPL?

**Comment by Yitzchok** [comment]
I think for starters we have to ensure that **.ConfigureAwait(false)** is called on every await method. Or we can use Fody to do it https://github.com/Fody/ConfigureAwait

**Comment by sipsorcery** [comment]
I actually meant TAP. 

I'm not so sure about a blanket adoption of `.ConfigureWait(false)`. I understand the potential benefits but I do like the idea of letting the runtime sort out the synchronisation context. I do like the changes from your PR that got rid of the extra `await` calls and simply return the `Task` object to the caller. That way in a lot of cases, not all, it can be left up to the application if they want to throw the ConfigureWait switch. One possible gotcha with it is having to do extra invoking back on the UI thread in places it wasn't required before.

**Comment by Yitzchok** [comment]
Do your own research regarding using .ConfigureWait(false) in library code.

I have sadly wasted way to much time with async deadlock issues and also thought that I can avoid .ConfigureWait(false) because it makes the code look un-clean.

As a library that isn't involved with the UI there is no getting away with it and would be glad to be proven wrong.

Regarding the UI having to do more work. If you are trying to say that if we use ConfigureAwait(false) the UI code will have to do something special to get the rest of the call to their UI thread. It's not how it works. It works like this the context is stored when a Task is awaited so if somewhere down the line some code says I don't care about the context only the code after that call will have the context removed but when it returns to the main calling awaiting code that still has the context attached and will return to the UI thread.

**Comment by sipsorcery** [comment]
Implementation Notes:

There's a mountain of documentation on `async/await` and `TAP`. The implementation in this library has focused on the guidelines in [Async/Await - Best Practices in Asynchronous Programming](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming) which are summarised as:


Name | Description | Exceptions | sipsorcery status
-- | -- | -- | --
Avoid async void | Prefer async Task methods over async void methods | Event handlers | Done
Async all the way | Don’t mix blocking and async code | Console main method | Done
Configure context | Use ConfigureAwait(false) when you can | Methods that require con­text | Case by case

### Avoid async void

A method signature of `async void` has the potential to crash the process due to an unhandled exception [[1](https://haacked.com/archive/2014/11/11/async-void-methods/)] [[2](https://blog.stephencleary.com/2012/02/async-and-await.html)].

> With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started.

````
private async void ThrowExceptionAsync()
{
  throw new InvalidOperationException();
}
public void AsyncVoidExceptions_CannotBeCaughtByCatch()
{
  try
  {
    ThrowExceptionAsync();
  }
  catch (Exception)
  {
    // The exception is never caught here!
    throw;
  }
}
````

**This is the most important guideline for the sipsorcery library. Originally there were numerous event delegates that had a void return type, particularly the two most critical of all `SIPTransport.SIPTransportRequestReceived` and `SIPTransport.SIPTransportResponseReceived`. Because the event handlers would often have async calls they would end up becoming `async void`. The event delegates have now been converted to use a `Task` return type instead of `void`.**

### Async all the way

This guideline boils down to don't use any of:

 - `Task.Wait` or `Task.Result` (the latter is ok on a completed task).
 - `Task.WaitAny`
 - `Task.WaitAll`
 - 'Thread.Sleep`

The use of theses calls (excepting `Thread.Sleep`) was not widespread in the sipsorcery code and they have been eliminated except for a few minor cases in unit tests which will be cleaned up over time.

### Configure context

This guideline recommends setting the "continued on" context for an awaited task as arbitrary. This is particularly relevant for GUI apps where all completed awaited tasks will be continued on the main UI thread.

But there is a catch:

> You should not use ConfigureAwait when you have code after the await in the method that needs the context. For GUI apps, this includes any code that manipulates GUI elements, writes data-bound properties or depends on a GUI-specific type such as Dispatcher/CoreDispatcher. 

Applying this guideline to the sipsorcery is considered a work in progress. It does need careful consideration.

**Comment by sipsorcery** [comment]
Done in #144.

**Comment by Yitzchok** [comment]
@sipsorcery thanks for looking into this.

Regarding ConfigureAwait(false) in the library part of the source (not talking about in the examples projects), I don't see where we would need to keep the sync context. Can you point out an example of where it would be important?

**Comment by sipsorcery** [comment]
One case that needs to be tested is whether access to socket handles (used in the SIP and RTP channels) works properly with `ConfigureAwait(false)` that results in the same handle being used on two different threads.

That's way I put it as case-by-case. If we think it's warranted and have tested in both Console and GUI apps then `ConfigureAwait(false)` could be a good idea.

**Comment by Yitzchok** [comment]
Sockets shouldn’t need SynchronizationContext. If there is a threading issue then it will have to be resolved in another way since there is no one that ensures you will have the sync context ConfigureAwait false only says that I don’t care about the context from here on but someone before might have already remove the context. And in .net core 3 I think only WPF and WinForm have the context setup. 

The good part of ConfigureAwait(false) is that if used where it shouldn’t it will throw an exception right away.

**Comment by sipsorcery** [comment]
Proposed guidelines to address in #164.
