### ISSUE TITLE
SIPUDPChannel.SendAsync returning Success after BeginSendTo

### ISSUE THREAD

**Issue by Yitzchok** [sipsorcery/sipsorcery#150]
Returning Success right after calling BeginSendTo doesn't seem right and the exceptions there that it's trying to catch will probably never be caught.

https://github.com/sipsorcery/sipsorcery/blob/e28136f6d90b9eb924835f8d11133da339e54922/src/core/SIP/Channels/SIPUDPChannel.cs#L153-L154

**Comment by sipsorcery** [comment]
The challenge here is that there are currently 4 distinct channels all requiring different send calls. To support the `SendAsync` method on the `SIPChannel` class there was some retrofitting required on channels that didn't have a suitable `Task SendToAysnc` method. The `UdpChannel` is one of those.

The [BegindSendTo](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.beginsendto?view=netframework-4.8) indicates only a limited number of exceptions should be thrown `ArgumentNullException`, `SocketException`, `ArgumentOutOfRangeException`, `ObjectDisposedException` and ``SecurityException`. Errors like the remote party rejecting the packet are caught in the `EndSendTo` method.

Coincidentally I happened to today notice that the remote end point does get set when an ICMP packet is received rejecting a UDP packet:

````
int bytesRead = m_udpSocket.EndReceiveMessageFrom(ar, ref flags, ref remoteEP, out var packetInfo);
````

The `remoteEP` is getting populated for a 0 byte receive. That means the problem that's the root cause of the comment below and that's been annoying me for 10+ years may finally have a solution.

````
// ToDo. Pretty sure these exceptions get thrown when an ICMP message comes back indicating there is no listening
// socket on the other end. It would be nice to be able to relate that back to the socket that the data was sent to
// so that we know to stop sending.
````

But despite all that I think what you're getting at is that a send failure that results in an exception in `EndSendTo` doesn't get passed onto the application. That is intentional. SIP has a retransmit and timeout mechanism and they are what will eventually inform an application if a request couldn't be sent. With UDP in particular there's no guarantee a send got through even if no exception is thrown. If no response is received during the timeout period the application can catch the `SIPTransaction.TransactionTimedOut` event to be alerted of the failure.

**Comment by Yitzchok** [comment]
Thanks for explaining
