### ISSUE TITLE
Add Contact header parameters to REGISTER and INVITE

### ISSUE THREAD

**Issue by RoryRoberts** [sipsorcery/sipsorcery#176]
I'd like to be able to add some Contact header parameters when making a `REGISTER` or `INVITE` request. I achieved this in a fork by overriding `SIPRegistrationUserAgent.GetRegistrationRequest()` and `SIPClientUserAgent.GetInviteRequest()`, calling the base and modifying the return value. 

I'm wondering if it would be appropriate to inject these parameters into the constructor of the `SIPRegistrationUserAgent` (though I note that the constructor is quite big already) and inject it alongside the `SIPCallDescriptor` in `SIPClientUserAgent.Call`, or add it as a settable property on the `SIPCallDescriptor` itself.

**Comment by sipsorcery** [comment]
What about adding a callback function to each of those two classes along the lines of:

`public Func<SIPRequest, SIPRequest> AdjustInvite;`
And called as:
`switchServerInvite = AdjustInvite != null ? AdjustInvite(switchServerInvite) : switchServerInvite;`

That way it's not something developers have to be aware of or know about unless they explicitly need to adjust the request since that is going to be a very rare use case. It also gives maximum flexibility in that the `INVITE`/`REGISTER` request can be adjusted completely.

**Comment by RoryRoberts** [comment]
Thanks for the response and suggestion Aaron! That sounds very sensible, moves the edge case away from the typical usage, but allows the functionality for anyone who needs it.

If you're absolutely fine with me extending the classes in this way, I'm happy to work on this and submit a PR for it soon.

**Comment by sipsorcery** [comment]
Yes I'm fine with that approach.

**Comment by ernestopedrosa** [comment]
Hi!
Is there a way to do something like this but instead using SIPUserAgent on a transfer call (blind or attended)? I really need to pass a couple custom headers along when transferring a call. 
really appreciate any help!
Best
