### ISSUE TITLE
Define Audio Device

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#185]
How to define wich Audio device In and Out will be used when more than one?

**Comment by sipsorcery** [comment]
This part of the library doesn't deal with audio devices at all (mainly because the effort to do so in a platform independent way is a big chunk of work).

If you're using the SoftPhone example then it's using the Windows specific `RtpAVSession` from the [SIPSorceryMedia library](https://github.com/sipsorcery/sipsorcery-media/blob/master/src/RtpAVSession/RtpAVSession.cs) which in turn uses NAudio. The output audio device can be set on the `WaveOutEvent` instance but I haven't provided an option to do so. 

If that is what you're after I can add it as a future feature?

**Comment by rodolphopedra** [comment]
Yes!!!

**Comment by sipsorcery** [comment]
The softphone has a new [app config](https://github.com/sipsorcery/sipsorcery/blob/master/examples/Softphone/App.config) setting `AudioOutDeviceIndex` which can be used to set the audio output device. Setting to `-1` means use the default system device,
