### ISSUE TITLE
Delay in audio conversion [FFMPEG]

### ISSUE THREAD

**Issue by TheSuunny** [sipsorcery/sipsorcery#187]
Hi again, I didn’t notice yesterday that FFMPEG starts to send output data to StandardOutput.BaseStream only after 10 seconds, although they have already arrived at OnRtpPacketReceived. In this case, sound is recorded from the very beginning, and there is no deformation. Perhaps you know how this can be accelerated? I need to transfer sound to another application in real time, no delay in 10 seconds.

FFMPEG:

```
new ProcessStartInfo
{
    FileName = "ffmpeg",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    RedirectStandardInput = true,
    Arguments = "-f mulaw -ar 8k -ac 1 -i pipe: -vn -b:a 192k output.mp3"
};
```

**Comment by sipsorcery** [comment]
I'm not that familiar with the ffmpeg options that control buffering. The only hint I can suggest is having a look at `-quality realtime`. I've used that for real-time video processing in the past.

Have you had a look at `PortAudio`? It works on Linux and there's a nuget package for it. It could potentially save you having to pipe out to a separate process which is always going to be a bit fragile.

**Comment by apdevelop** [comment]
`NAudio` supports encoding (using `Media Foundation Transforms` internally) to MP3 too: [Encode to MP3](https://github.com/naudio/NAudio/blob/master/Docs/MediaFoundationEncoder.md)

**Comment by TheSuunny** [comment]
Oh, I didn’t even know about portaudio, on Nuget there are 2 packages, PortAudioSharp and portaudio, is that it?

For the most part I need to convert not even to mp3, but in order to get a stream output, in FFMPEG I did it through pipe:1 and `-f s16le -ar 48000 -ac 2`. How to do it with NAudio, I still do not understand

**Comment by apdevelop** [comment]
Do you need some explanations how to stream `NAudio` output to pipe (not to file) using C#  ?

**Comment by TheSuunny** [comment]
> Do you need some explanations how to stream `NAudio` output to pipe (not to file) using C# ?

Yes, I did not find anything sensible about this, only related to files

**Comment by sipsorcery** [comment]
Is your goal to record the audio to a file? Or do you need to playback the audio?

If you're attempting to record the audio `NAudio` may actually work for you on Linux. `NAudio` is .Net Standard compliant so it can run on Linux. It will fail as soon as it tries to use any physical devices since it relies on Windows dll's. To record audio there's no need to access any devices so maybe it's suitable?

If not can you describe your scenario a bit further.

**Comment by TheSuunny** [comment]
> Is your goal to record the audio to a file? Or do you need to playback the audio?
> 
> If you're attempting to record the audio `NAudio` may actually work for you on Linux. `NAudio` is .Net Standard compliant so it can run on Linux. It will fail as soon as it tries to use any physical devices since it relies on Windows dll's. To record audio there's no need to access any devices so maybe it's suitable?
> 
> If not can you describe your scenario a bit further.

I want to get a sound, then convert it to the format I need, using FFMPEG I set the parameters like `-f s16le -ar 48000 -ac 2`, after which I want to transfer the received data from conversion to another application. 

Using for example StandardOutput (BaseStream) in FFMPEG. I managed to do this through FFMPEG, but there is a delay of 10 seconds.

**Comment by sipsorcery** [comment]
Here's an [example](https://github.com/sipsorcery/sipsorcery/blob/8956b88474eabc25b2857222ab492e981806b74e/examples/SIPCallResampleAudio/Program.cs#L85) of the simplest/crudest way to resample  audio RTP packets to a higher sampling rate in real-time. The example uses NAudio but I've tested it on Linux and it works correctly, which is expected since no devices are involved.

The resampling in this case simply copies each sample 6 times (48000/8000). It sounds ok for audio that's mainly voice but I suspect it wouldn't sound so great for music. An in depth article about audio conversions and resampling is available [here](https://www.codeproject.com/Articles/501521/How-to-convert-between-most-audio-formats-in-NET),
