### ISSUE TITLE
Recommended way to use a Public IP address in a SIP server - SIPPacketMangler

### ISSUE THREAD

**Issue by paulnearney** [sipsorcery/sipsorcery#190]
I've deployed my SIP server to an internet-facing server, but it's responding to the INVITE with the private IP address in the SDP and Contact header.

I can see the SIPPacketMangler looks like a good solution to this, as long as I can provide the public IP address. However, I can't determine where the best place to apply the mangler in code is. I can see numerous options, but before I go ahead, I wanted to check to see if there is a recommended way of integrating this, or an example (couldn't find it used in any of the SipSorcery examples)

**Comment by paulnearney** [comment]
Hmmm, possibly scratch that. Looks like ContactHost on SIPTransport controls the Contact header. Is there a similarly straightforward way to control the host IP address in the SDP response? I'm currently patching it in to RTPSession.createOffer, but this feels wrong.

**Comment by sipsorcery** [comment]
`ContactHost` for the `SIPTransport` public host or IP address is the correct way.

Below I've outlined the current state of the SDP/RTP side of things. The TLDR; is that it's still a work in progress and feel free to provide an outline of your scenario so that it can be considered.

For the RTP/SDP it's not as clean. I recently removed the SDP mangling from the `SIPClientUserAgent` with the last version it was present being [4.0.29-pre](https://github.com/sipsorcery/sipsorcery/blob/9f01c2e64d2d22623d53af69b34e6c470865e5d4/src/app/SIPUserAgents/SIPClientUserAgent.cs#L259). 

The `SIPPacketMangler.MangleSDP` call that was previously used in that class works for a narrow set of use cases but it was never ideal and now is the time to fix it.

One of the big dilemas the library has been going through in the last few months is the interaction between handling the SDP and the `RTPSession` including its child classes. Initially SDP was kept completely separate from `RTPSession` but then eventually found it's way back in as the only common point to generate and process it. At the same time creating the new `RTCPeerConnection` class for WebRTC has had an influence and meant the SDP management is attempting to be done in a generic way rather than just for SIP/VoIP. For example WebRTC uses ICE which puts the IP addresses in ICE candidates rather than SDP `Connection` lines (ICE also solves the problem of needing to do any IP address mangling but that does't help for SIP/VoIP devices that don't support it).

The mechanisms could change a little bit and I've already spotted and fixed one bug that was setting the IP address incorrectly in the SDP answer. If you do need to set the SDP connection IP address then at this stage the most correct place is likely to be after calling `RTPSession.CreateOffer` or `RTPSession.CreateAnswer`. You should set the address directly using the `SDP.Connection.ConnectionAddress` property and not by using the fragile string manipulation from `SIPPacketMangler.MangleSDP`.

I'll put some more thought into this over the coming days and provide an update if I can come up with a better approach.

**Comment by paulnearney** [comment]
Thanks Aaron, that makes a lot of sense. At this stage, I'm just standing up a very basic SIP server (no WebRTC) on an internet-facing machine, so need to provide the public IP adress so it can be used in the offer and contact header. I'm happy to hard-code this for now, but I can see that I'll need something more sophisticated at a later date. It looks like you found a good solution in #97, so I'll give that a try.

**Comment by bob-dawson** [comment]
for SIP server, I think this could be made simpler: the SIPUserAgent.Answer should take a sdp address parameter, and then pass to AnswerSyncronized, then AnswerSyncronized use that to call MediaSession.CreateAnswer, which now is null.  I've test this, and it works.  To keep compatible for the API, the new parameter could have a null default value, which will not break old code.
