### ISSUE TITLE
Microphone Icon shaking

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#191]
When there is a connection in progress, the microphone icon next to the windows 10 clock is shaking

**Comment by sipsorcery** [comment]
That's an Operating System feature to let you know your microphone is being used. Same thing occurs if your browser or any other application accesses the microphone.

**Comment by blendR8** [comment]
I have the same problem. I know that the icon appears if a software is using the microphone but in my case it goes on and off as long as the call is active, so it  is shaking like rodolphopedra said

**Comment by sipsorcery** [comment]
Does the same thing happen with other softphones like [MicroSIP](https://www.microsip.org/)?

**Comment by rodolphopedra** [comment]
With 3CX, no.

**Comment by sipsorcery** [comment]
The audio capture logic in the example apps all use basic functions from [NAudio](https://github.com/naudio/NAudio). To track this issue down I'd recommend seeing if you can duplicate the problem with one of the NAudio samples and possibly see if it's a known issue there.

**Comment by blendR8** [comment]
I can't duplicate the problem if I build a record WPF with nAudio. The mic symbol stays without going on and off

**Comment by alextatham** [comment]
Is there anything I can do to help fix this.  I'm attempting to build with NAudio now but not got very far yet.

**Comment by Yitzchok** [comment]
https://github.com/sipsorcery/sipsorcery/pull/148

**Comment by sipsorcery** [comment]
I've applied Yitzchok's suggestion of increasing the NAudio input buffers and pushed a new  `SIPSorceryMedia` muget version.

I'm flying blind here as I haven't observed the same behaviour and can't test.

**Comment by alextatham** [comment]
I'll test now.

**Comment by maddinthegreat** [comment]
@sipsorcery:
No that's NO feature. I use CSCore (similar to NAudio) and when I record something thru CScore, there's no flacking.
I didn't investigate what your are doing in the code, but i think you are pollling or something.
It's absolutly a coding issue.
I'll later on into this.

Regards

**Comment by alextatham** [comment]
Update on testing.  I downloaded the master branch from the sipsorcery-media repository.  I completed the vcpkg steps.  I compiled the branch in VS 2019 Preview, Debug, x64 which produced the 3 DLL files.  I had a problem replacing the existing NU-Get packages in the examples so backed up and then replaced the DLL files in c:\users\me\.nuget\packages\sipsorcerymedia\4.0.42-pre\build\x64.  Rebuilt the examples and checked that the bild directories were using the new DLL files.  Ran the Softphone example and the microphone issue is resolved.  Tested again with a live SIP server and there is two way audio.

Replaced the DLL files in the debug path and ran the softphone again and the microphone flashes away as before.

Swapped back to the new DLL files and although if you make several calls you do see the microphone flash occasionaly the issue is 95% better.

**Comment by alinoob** [comment]
I figured out, if you deactivate your microphone in Windows then activate it again, it won't occur.

I am using the latest Windows 10 Pro Build with SIPSorcery -v 4.0.58-pre.

**Comment by sipsorcery** [comment]
The [SIPSorceryMedia](https://github.com/sipsorcery/sipsorcery-media) library has been largely replaced by the [SIPSorceryMedia.Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows) library. The new library is now being used in the Softphone and other SIP example projects.

Both libraries use NAudio for accessing the microphone and the code calling NAudio is pretty much identical. The new library is now C# only (native libraries are accessed with PInvoke) which means it's a lot easier to debug problems like this. I have still not experienced the issue on my Windows 10 machine.

If anyone is still interested in this issue and is able to obtain any further info please feel free to re-open.

**Comment by alextatham** [comment]
I'd like to re-open this one.  I can re-create this and I'm working on it now.
