### ISSUE TITLE
Use Library to Connect to a SIP Server

### ISSUE THREAD

**Issue by jogibear9988** [sipsorcery/sipsorcery#202]
Is it possible to use this Library to connect to a SIP Server (i've the DNS, Username(is the phone number) and Password) and then Listen to calls.
So I get an event when sombody calls the Number.

I'm not getting it from the examples...

**Comment by sipsorcery** [comment]
Yes indeed it's one of the core uses of the library.

The trick is there are two distinct steps:

 1. You need to create a registration with the SIP server using the `SIPRegistrationUserAgent` class,
 2. Listen for incoming calls and accept them with the `SIPUserAgent` class.

There is no exact example for this but there are two that can be combined. The [UserAgentRegister](https://github.com/sipsorcery/sipsorcery/tree/master/examples/UserAgentRegister) example does the first step and the [RecordIncomingCall](https://github.com/sipsorcery/sipsorcery/tree/master/examples/RecordIncomingCall) should be close to what you want for the second.

**Comment by jogibear9988** [comment]
Works like a charm...

I only need to add the OnRequest callback from the RecordIncomingCall.

Thanks...

**Comment by jogibear9988** [comment]
@sipsorcery 
one more question, can I also use the "SIPRegistrationUserAgent" to dial?

**Comment by sipsorcery** [comment]
No you can't. "Dialing" involves SIP INVITE requests. "Registering" involves SIP REGISTER requests. The two operations are completely separate (even though for incoming calls they end up being linked). Hence the need to keep things flexible and have different classes for each.

**Comment by jogibear9988** [comment]
The I need to use the SIPUserAgent

But for me this not clear.

the Call Method only has a Argument for Destination, User and Password.
Do I not need the server for this then?

**Comment by jogibear9988** [comment]
Sorry for my dumb questions

**Comment by sipsorcery** [comment]
The reason there are multiple user agents that each carry out a particular task is because with SIP there is no one size fits all. Initially all you may want to do is make and receive calls and yes it would be possible to have one class that does that. But then you might want to do transfers or manage Message Waiting Indications with your registrations and the list goes on. 

The `SIPUserAgent` class is actually a relatively new class and was created to cover the most common scenario people were asking for which was an easy way to make and receive calls and a few other common things like hold and transfer. It's definitely a good place to start.

If you're attempting to create a SIP server application things get trickier. In that case I'd suggest looking at the [SIPCallServer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPCallServer) example as a starting point.

Once you scratch the surface with SIP it can get a bit overwhelming. You'll probably need to take a bit of time to read some tutorials about the fundamental mechanisms.

**Comment by jogibear9988** [comment]
I don't think I want to create a server application. (I think, but don't know)

At the moment I use a softphone in wich I enter my user credentials and my server ip.

This Softphone Displays when somone is calling me (wich now also works using your library).

The other thing is, I want to call a telephone number (via my server account?) and like to play a wave file.


I'll look that I read a bit more about SIP/SDP and RTP.

But the scenario I wanted to do is possible?

**Comment by sipsorcery** [comment]
Yes it's possible. That's exactly what happens when you call someone via the softphone example and press the hold button.
