### ISSUE TITLE
Registration expiry returned not taken into account

### ISSUE THREAD

**Issue by sw-ch** [sipsorcery/sipsorcery#21]
Dear Aaron

First of all, I wanted to thank you for the effort you put into this project. It helped me a lot to get into the whole SIP topic.

I have a question regarding the expiry value that is being extracted from the registration response. If only one contact header is present, everything works. If I have two or more registered UAs for the same SIP account, the extraction isn't working as expected. I'm not sure if I mixed things up, but to find the matching expiry value, you're comparing the header contactURI against the sipAccountAOR.

I get the desired behavior if I change:
```
                    foreach (SIPContactHeader contactHeader in sipResponse.Header.Contact)
                    {
                        if (contactHeader.ContactURI == m_sipAccountAOR)
                        {
                            contactExpires = contactHeader.Expires;
                            break;
                        }
                    }
```

to:
```
                    foreach (SIPContactHeader contactHeader in sipResponse.Header.Contact)
                    {
                        if (contactHeader.ContactURI == m_contactURI)
                        {
                            contactExpires = contactHeader.Expires;
                            break;
                        }
                    }
```
In SIPRegistrationUserAgent.cs

You don't, by accident, know what I'am doing wrong?

**Comment by sipsorcery** [comment]
Yep that looks like a bug. The contact URI in the registration binding is unlikely to ever match the m_sipAccountAOR. I've committed the fix for that now.

Note that sometimes even checking the m_contactURI will fail if there is a nasty NAT/SIP Application Layer Gateway involved that substitutes the private IP address in the contact URI for the public address. The way I've gotten around that for the sipsorcery.com service is to set a pseudo-random tag on the contact URI and check for that so it won't matter if the host portion of the contact URI is mangled.

**Comment by sw-ch** [comment]
Thanks for the quick reply. Regarding replaced IPs in contact URIs, I didn't stumble across that problem but will keep it in mind. I use a random rinstance tag per UA instance. So the fallback will be to take this into account as well.
