### ISSUE TITLE
Not possible to play audio file once

### ISSUE THREAD

**Issue by VsevolodKzn** [sipsorcery/sipsorcery#227]
Please add a feature to play audio file exactly once (useful for voice chat bots) and an event that is fired when audio playback is finished.

**Comment by sipsorcery** [comment]
Do you mean adding to the `IMediaSession` interface? Or do you mean incorporating it into the softphone or one of the other examples?

**Comment by VsevolodKzn** [comment]
I mean that now to play audio file I so something like:
    var audioOpts = new AudioOptions
            {
                AudioSource = AudioSourcesEnum.Music,
                SourceFiles = sourceFiles
            };
But this way file will be played in cycle. It might be good idea to add new member to  AudioSourcesEnum like VoiceMessage that can be used to play file once.

I'm not sure what will be the best place for event, but I think it's a good idea to have some kind of notice when playback is actually finished.

**Comment by sipsorcery** [comment]
I've done some work on the `RtpAudioSession` class so that it now supports interrupting the original source to send a stream to the remote party. A [PlaySounds](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/PlaySounds/Program.cs) example is also available.

If your intention is to play voice prompts to the remote party you may also find the new [Azure text-to-speech](https://github.com/sipsorcery/sipsorcery/blob/master/examples/AzureExamples/TextToPcm/Program.cs) demo useful. It can generate voice messages in a PCM 16k format that can be passed directly to the `RtpAudioSession` class.

**Comment by VsevolodKzn** [comment]
Looks great, thank you!
