### ISSUE TITLE
Creating UDP-SIPChannel fails, if called twice with same port but different AddressFamily

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#228]
Hey Aaron,
I do have an issue with creating UDP-SIPChannels
I've always created my SIPChannels with specifying IPAddress.Any and IPAddress.IPv6Any and port 5060

Creating the SIPChannel for IPv4 socket first makes it impossible to create the IPv6 socket (AddressAlreadyInUseException)
Creating the IPv6 socket first, binds the IPv4 socket also (due to DualStack) and creating IPv4 socket second fails in succession (AddressAlreadyInUseException).

When the udp-sockets where created by using .Net UDPClient this issue did not exist (many years ago).

Removing the SetSocketOption(ExclusiveAddressUse) in NetServices.CreateUdpSocket solves creating IPv4 socket first and IPv6 socket second and vice versa

I guess, if one creates IPv6 socket, one has to know or live with it, that DualStack will be used (if supported by OS), but there could be the possibility that this is not a desired behavior?

Side-note: the ExceptionMessage in NetServices.CheckBindAddressAndThrow sais "RTP socket" allthough the method is used in non RTP context, too

ciao Ralf

**Comment by sipsorcery** [comment]
Hi Ralf, the reason for adding the `ExclusiveAddressUse` socket option was a result of tracking down a bug where an IPv6 dual mode RTP socket was not able to receive any packets because an IPv4 SIP socket was bound on the same port. I'd always understood that the OS should have prevented that from happening, i.e. if an IPv4 socket was bound to a port than an attempt to bind a dual mode IPv6 socket on the same port should throw an exception and vice-versa. 

It was a very tricky bug and took me a few days to track down. It's also a nasty one as everything seems to be alright but no RTP packets ever arrive.

I've put in a [bug report](https://github.com/dotnet/runtime/issues/36618) on the dotnet core repo but doubt it will be fixed any time soon hence the introduction of the `ExclusiveAddressUse` option.

Bearing in mind that due to this socket bug it's not possible to go back to the old behaviour (you were most likely able to get away with it because in your case both your sockets were being used by the same SIP transport) perhaps the best solution is to make SIP UDP sockets default to dual mode IPv6 as well? What do you think?

**Comment by rj2Skipper** [comment]
all in all this only applies to connectionless sockets (e.g. UDP)
if a socket is bound in windows without any option, it has neither option set (ExclusiveAddressUse or DualMode or ReuseAddress)

Maybe it's best to leave the Exclusive socket option set, but do not create IPv6 Sockets in DualMode  or implement an option to influence DualMode socket binding or setting SocketOption.IPv6Only ?
That way users control and get context specific exceptions when creating sockets for SIPChannel or RTP that are allready bound by other applications

**Comment by sipsorcery** [comment]
Feel free to re-open if this is still a problem.
