### ISSUE TITLE
SIPDialogue does not hang up

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#23]
Calling via https://github.com/sipsorcery/sipsorcery/blob/master/sipsorcery-core/SIPSorcery.SIP.App/SIPUserAgents/SIPServerUserAgent.cs 
dialog state is "Unknown"
Calling into
public void Hangup(SIPTransport sipTransport, SIPEndPoint outboundProxy)
with sipTransport = a value, and outboundProxy as null

No exception is thrown
No message appears in the logging anywhere

When the client hangs up, a "unmatched BYE request received" is logged

**Comment by rwil02** [comment]
Hmm.
Maybe I am getting an error:
2017-02-20 10:35:17,060 [siptransport-reliables] ERROR sipsorcery.sip [(null)] - Exception SIPTransport ProcessPendingRequests checking pendings. Object reference not set to an instance of an object.

**Comment by rwil02** [comment]
Manually gone through all the steps in https://github.com/sipsorcery/sipsorcery/blob/master/sipsorcery-core/SIPSorcery.SIP.Core/SIP/SIPDialogue.cs  
Hangup()
Every step returned what appears to be a valid result.
Could this be related to:
Caching DNS lookup failure for IN-SRV-_sip._udp.xxxx.xxxx.xxxx. error was DNS response had no answers?

**Comment by sipsorcery** [comment]
Is the transport UDP or TCP? The [siptransport-reliables] thread is only for the reliable TCP and TLS transports.

The DNS lookup can potentially stop the SIP BYE request from reaching it's destination but getting an error on the SRV record lookup is pretty normal. The proxy will fallback to trying the A record and is more likely to b successful with it.

The "unmatched BYE request received" message may be because you haven't stored the Dialogue object you got back from the SIPServerUserAgent Answer method. There is nothing in the code that automatically stores Dialogue objects for you so you'll need to use a List or Dictionary etc. The main sipsorcery application uses the SIPDialogueManager backed by a MySQL database for this purpose.

**Comment by rwil02** [comment]
Thanks for that.  I only get the "BYE" issue after the attempted server hang up, so if I can resolve that I think I'll be good.  

The transport is udp , but it's not like I'm making the choice about using it, I'm just calling "Hangup"

The Answer method stores the dialogue it returns internally in m_sipDialogue.  Since I'm running this as a singleton, that should still be the correct dialogue I would think?  At least m_UAS.SIPDialogue.Hangup is what I'm calling.

Now if I could just figure out why I'm connecting to server pan.aabb.net and the dialogues are for devices at XXXX@as.aaCbb.net (and as.aaCbb.net doesn't exist as a domain) - which is where I think the BYE is failing.

**Comment by rwil02** [comment]
OK.  the BYE fro the client (which works) is
BYE sip:10.2.1.35:5067 SIP/2.0

The BYE from the server is:
BYE sip:021325123@as.wxcnz.net:5060;maddr=182.154.16.150;transport=udp SIP/2.0

which seem fairly radically different, so I'm going to focus my attention there.

**Comment by sipsorcery** [comment]
Very very late here but the problem was most likely due to a Contact SIP URI in the client's INVITE request not being set correctly or in a way the application could handle.

The BYE request sent by the server will be sent to the SIP URI that the client provides in the INVITE request Contact header. If server can't reach the end point specified by that URI then the BYE request will never reach the client.
