### ISSUE TITLE
Can't init SIPUDPChannel for Framework 4.7.2 target

### ISSUE THREAD

**Issue by RomanPlekhanov** [sipsorcery/sipsorcery#234]
I made a console application with classes from the softphone example. Target Framework 4.7.2. When I run the application then a FileNotFound exception occured. 
![image](https://user-images.githubusercontent.com/31315091/84083570-94ac9080-a9ea-11ea-9637-404d811daa52.png)

I installed System.Collections.Concurrent package but it not help.
![image](https://user-images.githubusercontent.com/31315091/84084062-72674280-a9eb-11ea-8961-2b711d2572f9.png)

**Comment by sipsorcery** [comment]
I recall someone else having a similar issue a while ago and it ended up being an incorrect package version or reference or something like that. Have you tried a `clean` and `rebuild`?

Failing that you can try building the [.Net Framework Getting Started Example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/GetStartedNetFramework). It's part of the CI and builds fine with a target of `4.7.1` or `4.7.2`.

**Comment by RomanPlekhanov** [comment]
I tried an echo-test. There are still noises. This is a new dump of an
echo-test.

ср, 10 июн. 2020 г. в 20:30, Aaron Clauson <notifications@github.com>:

**Comment by RomanPlekhanov** [comment]
I tried an echo-test. There are still noises. I sent a new dump of an echo-test. Check you email.

**Comment by sipsorcery** [comment]
I didn't get any attachment.

**Comment by RomanPlekhanov** [comment]
https://yadi.sk/d/lSZBVHLdIttyAA

**Comment by sipsorcery** [comment]
The latest trace is worse than your original one. I can't really guess what's going wrong because the RTP stream deviates so far from what's expected. I've included some observation points as well as more RTP analysis graphs from WireShark showing your results compared to mine.

 - The RTP stream from your end (running the sipsorcery example) only has half the number of expected packets. It seems as if your microphone is generating samples at 40ms intervals instead of 20ms. But then the samples are still the correct size for 20ms so it doesn't make sense. Have you changed any of the parameters on the input device in `WindowsAudioRtpSession`?

`WaveFormat _waveFormat = new WaveFormat(8000, 16, 1);`

 - The static you hear on the audio stream is due to RTP packets being received too late. The jitter on packets being sent from your end is jumping around a lot. This would seem to indicate your machine is CPU bound and not able to deliver the RTP packets consistently. This is also strange as the CPU usage should be only 2 or 3% at most.

 - To rule out your microphone you can try using one of the signal generator sources. These do not work perfectly with the .Net Framework due to the `Timer` resolution I mentioned previously but they if your system is not CPU bound they should be able to deliver RTP packets a lot better than what's showing up in your traces. The lines to change are shown below, note that you won't hear anything after making the change as the speaker is not used. Let it run for 30s or so and you can then listen to the stream with WireShark.

````
//var rtpSession = new WindowsAudioRtpSession();
var rtpSession = new SIPSorcery.Media.RtpAudioSession(new SIPSorcery.Media.AudioSourceOptions { AudioSource = SIPSorcery.Media.AudioSourcesEnum.SineWave }, null);
````

**Your Results:**

![rtp_packet_count_bad](https://user-images.githubusercontent.com/197660/84391368-cf801580-abf0-11ea-8d2f-221a0a988462.png)

![rtp_stream_ba](https://user-images.githubusercontent.com/197660/84391391-d73fba00-abf0-11ea-9732-ce74a24d3fc2.png)

**My Results:**

![rtp_packet_count_good](https://user-images.githubusercontent.com/197660/84391426-e161b880-abf0-11ea-9a59-f9cf14bb0f17.png)

![rtp_stream_good](https://user-images.githubusercontent.com/197660/84391433-e6266c80-abf0-11ea-8f07-8ad0d0947f23.png)
