### ISSUE TITLE
streaming video using vp8 and joining in the middle problem

### ISSUE THREAD

**Issue by AliMiriGitHub** [sipsorcery/sipsorcery#236]
Hello,
you have two projects named "WebRTCReceiver" and "WebRTCServer"
with "WebRTCReceiver" we can receive video from a browser and then decoding it using vpxEncoder and watch it.
with "WebRTCServer" we can stream a video from a file and then encoding it using vpxEncoder and pass to the browser.

I've currently developed a video conference .net core web application using your sipsorcery project.
I don't want to get a vp8 RTP packet from the browser and then decode it to i420 in the server and then encode i420 to vp8 again and pass it to browser, because of server performance.
so I directly get vp8 from the browser and pass it to peer connections without converting. It works perfectly.

my problem is receiver video peer should listen to video from beginning and if joining from the middle cannot watch it, I think the vp8 RTP packet received from the browser hasn't header to point next video frame, and this information only available in the first packet that working when streaming from the first. (this problem does not exist in vp8 frame generated by vpxEncoder i420).

I worked several days on this problem and yet can't resolve it, please help me if possible.
thanks.

[VideoAndVoIPProjects.zip](https://github.com/sipsorcery/sipsorcery/files/4777225/VideoAndVoIPProjects.zip)

**Comment by sipsorcery** [comment]
The first problem is you shouldn't be forwarding RTP packet headers that you receive on one WebRTC or RTP Session to a different session. The RTP headers are connection specific. The SSRC header should be unique across sessions. Actually thinking about it some more you might get away with forwarding full RTP packets from one connection to another BUT I wouldn't recommend this approach. I don't think it would take much for something to break it.

To remedy the problem instead of using the `SendVp8VideoPacket` method you added you should use the existing `SendVP8Frame` after you receive a full frame from the sender. The `WebRTCReceiver` example has the [RtpSession_OnRtpPacketReceived](https://github.com/sipsorcery/sipsorcery/blob/df0594692b793e11e2e87d8f8094bfdfd3bdf1b6/examples/WebRTCExamples/WebRTCReceiver/Program.cs#L218) method that shows you how to wait for a full frame. Note you don't have to decode the frame, since you want it VP8 encoded, but you do need to reconstruct the frame from the individual RTP packets before forwarding it.

The situation with audio is easier (note there's no such thing  as VP8 audio, most likely you're receiving PCMU). Every RTP packet will always contain a full frame so you can call the `RTPSession.SendAudioFrame` method on the destination session and the buffer is the `RTPPacket.Payload` on the received packet. No need to put frames back together.

**Comment by AliMiriGitHub** [comment]
Thanks for your help, I used your approach, `SendVP8Frame` after waiting and receiving a full video frame from the sender and `SendAudioFrame` for sending audio but the problem still not solved (if the receiver starts before the sender it works fine but if the receiver joins after or middle of stream cant watch it.)

 I've used this approach before and it didn't work, I think the **full-frame** that comes from the browser (chrome or ....) is still related to other **full-frame** (maybe some pointing is between them) because its only work if it starts from first full-frame (this does not happen when we stream media from file `SIPSorceryMedia.MediaSource` and then Encode it to vp8 and sending)

I attach a simple project that has this problem.

[SampleWebRTCServerSendAndReceive.zip](https://github.com/sipsorcery/sipsorcery/files/4778923/SampleWebRTCServerSendAndReceive.zip)

**Comment by sipsorcery** [comment]
This goes a bit out of my area of expertise now but I suspect the problem could be the VP8 key frame interval. A VP8 decoder can only start decoding once it receives a key frame. In my very crude encoder implementation I set the [key frame interval](https://github.com/sipsorcery/sipsorcery-media/blob/3a64e710b885c0d8c4d105205e68d36cb06b88fc/src/VpxEncoder.cpp#L70) to 1 every 20 frames.

Since I last looked at the VP8 stuff Google have added the `AVPF` early feedback profile to their WebRTC implementation and my guess is that the key frames are sent much less frequently than once per second and possibly don't get sent at all unless feedback is given that one is required. The Google VP8 encoder implementation is [here](https://chromium.googlesource.com/external/webrtc/stable/src/+/refs/heads/master/modules/video_coding/codecs/vp8/vp8_impl.cc#251).

You'll need to do a little bit of digging on this and if you do find anything I'd love to hear. It could be there's an advanced setting in Chrome that actually lets you set the key frame interval. Alternatively maybe there's a specific RTCP report that can be sent requesting an immediate key frame interval.

**Comment by AliMiriGitHub** [comment]
Thanks for your guidance, The problem was exactly the keyframe, I think I should implement `NACK PLI ` or `CCM FIR` because it's impossible to change the keyframe interval of the browser.
I'll inform you if I do it.

**Comment by sipsorcery** [comment]
I had a quick look at [RFC4585](https://tools.ietf.org/html/rfc4585#section-6.3.1) and sending an RTCP Feedback packet with a Picture Loss Indication (PLI) seems straight forward. Whether it would work just to send that one feedback packet in isolation without the general ACK/NACK mechanisms is the question.
