### ISSUE TITLE
AKA-MD5

### ISSUE THREAD

**Issue by Educsys** [sipsorcery/sipsorcery#245]
Does the library support akav1-md5 authentication?

**Comment by sipsorcery** [comment]
No. I haven't come across that scheme. Which device or software are you attempting to authenticate with?

**Comment by Educsys** [comment]
This is a system similar to openimscore. I can't register because the authentication algorithms don't match. Requires AKAv1-MD5

**Comment by sipsorcery** [comment]
I did a quick bit of research and it doesn't look that tricky to add support for AKAv1-MD5 (could be famous last words). The hardest part could end up being testing it. I typically test with Asterisk but while it seems to have had an option for akav1-md5 at one point it ended up getting removed because no one ever used it.

Are you going to be in a position to devote a bit of time to testing with your server? It would involve running small console apps and feeding me back the logs. Either that or step-by-step instructions on how to set up a free server of some kind to test with.

**Comment by Educsys** [comment]
I replied to an email about the server for testing. If necessary I can perform the necessary manipulations and tests

**Comment by sipsorcery** [comment]
Thanks for the further info, I've done some more researching and have a question.

Is it the case that to use the AKAv1-MD5 scheme the SIM card on the device needs to be involved? This StackOverflow [issue](https://stackoverflow.com/questions/39953009/sim-authentication) seems relevant.

**Comment by Educsys** [comment]
Perhaps I have not studied this topic enough myself. I'll take a timeout while I study. I don't have a SIM card on my device, so I probably need a different registration process.

**Comment by sipsorcery** [comment]
Feel free to re-open if more info comes to light.
