### ISSUE TITLE
No Incoming Call registered

### ISSUE THREAD

**Issue by alinoob** [sipsorcery/sipsorcery#251]
I ran the RecordIncomingCall Example and tried to call using my mobilephone but no incoming calls are detected.

`SIPSorcery Getting Started Demo
[11:38:41 INF] SIP UDP Channel created for 0.0.0.0:5060.
press any key to exit...`

I am using a Fritz!Box as Router and I call from my mobilephone.

At first, I thought I only listen to my router IP but that turned out to be not a great idea. Any idea why it is not working for me?

**Comment by sipsorcery** [comment]
To be able to record a call the demo application has to receive an incoming SIP call. The example doesn't do a packet capture or anything like that.

You need to work out how to get your Fritz!Box to forward the call it receives onto the example program running on your computer.

**Comment by alinoob** [comment]
Even if other Softphones do forward the call from Fritz!Box to my computer? I thought, I need to listen the 5060 of a specific port which isn't detected by the given example.

**Comment by alinoob** [comment]
I tried to run the SoftPhone Example and it outputs the following:

`System.ApplicationException: "Unable to bind UDP socket using end point 0.0.0.0:5060."`

**Comment by sipsorcery** [comment]
I don't mean to be harsh but most of the questions you are asking aren't really to do with programming the sipsorcery library. For general Operating System, VoIP, networking questions you may be better off on one of the Stack Exchange forums such as [Super User](https://superuser.com/).

The reason you can't bind to port 5060 is because you already have an application using that port, most likely a SIP Softphone. Close it and then you'll be able to use the port.

**Comment by alinoob** [comment]
I am sorry. I won't open any question issues.

Regarding the incoming call issue: You are right for the SoftPhone Example. For the RecordIncomingCall it still does not get any information on what has been received. I'll be working my way. Thanks and sorry again.
