### ISSUE TITLE
Running 4.0.60-pre .netFramework 4.7.2 Could not load type 'System.Security.SecurityRulesAttribute'

### ISSUE THREAD

**Issue by NemtsevSergey** [sipsorcery/sipsorcery#259]
Hello, do you have working example on .netFramework 4.7.2? On .netCore 3.1 it works greate.
Create clean WPF project on .netFramework 4.7.2, add nuget - SIPSorcery, SIPSorceryMedia - give error on build - Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Microsoft Visual Studio Enterprise 2019 
![1](https://user-images.githubusercontent.com/36694542/88740144-b2db7500-d17f-11ea-8b93-2971c5166525.PNG)
Version 16.6.3

**Comment by sipsorcery** [comment]
The `SIPSorceryMedia` package only supports .NET Core. It's a [C++/CX](https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx?view=vs-2019) component that targets `netcoerapp3.1`.

But you can probably do without the `SIPSorceryMedia` package. The plan is to deprecate it because of issues like this and also because it's Windows specific.

If you only want audio support on Windows you can use the [WindowsRtpAudioSession](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/Common/Devices/WindowsAudioRtpSession.cs) instead of the `SIPSorceryMedia` package. If you need video it's trickier.

**Comment by sipsorcery** [comment]
Feel free to re-open if there is any further info.

**Comment by NemtsevSergey** [comment]
It is ok, will use netcoerapp3.
