### ISSUE TITLE
Blindtransfer not working (Failed to transfer)

### ISSUE THREAD

**Issue by thornzz** [sipsorcery/sipsorcery#288]
Hi,

I have tested attended transfer is working but i could not working BlindTransfer. Its saying always Transfer Failed Declined. Our PBX system is 3CX. I can blind transfer with their softphone. Is there any idea?

**Comment by sipsorcery** [comment]
My guess is 3CX is expecting the `REFER` request to be authenticated.

Can you get the SIP response code for the `REFER` response or even better a full SIP trace of the blind transfer attempt.

For reference here's a screenshot of what should be happening and which is from the [Blind Transfer Test Scenario](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPScenarios/BlindTransferScenario). It shouldn't be too hard to fix once the cause is identified. Blind Transfers are much easier to deal with compared to Attended Transfers.

![image](https://user-images.githubusercontent.com/197660/90295734-a2b2dd80-de81-11ea-9488-c41056e43fde.png)

**Comment by thornzz** [comment]
Here is the SIP trace log.

https://prnt.sc/u007ku

**Comment by sipsorcery** [comment]
It looks like your 3CX server has accepted the Blind Transfer as the `REFER` request gets a `202 Accepted` response.

Perhaps the target of the transfer is rejecting it because it doesn't like something.

The contents of the `NOTIFY` request in from your trace may reveal something. Also the logs or a SIP capture of the device that's the target of the transfer may have something.

**Comment by thornzz** [comment]
Hi again,

Here is my fail and success pcap files full trace of sip capture.

### Fail : https://filebin.net/jd9oqa0w3k95817w/fail.pcap?t=60cm7sau
### Success : https://filebin.net/yw2mct79lpzm50gz/success.pcap?t=6xu03qat

Fail is got using with sipsorcery BlindTransfer method. Success is with using 3cx softphone. I could not notice anything wrong but i m not expert. Could you check it out?

**Comment by sipsorcery** [comment]
The `Refer-To` URI being sent from the sipsorcery end is most likely wrong. Technically it's a valid SIP URI nut I don't think it's what you meant. When initiating the BLind Transfer from the sipsorcery softphone try entering the full SIP URI, e.g. `sip:12@k2m.3cx.com` .

The screenshot below is from the failed trace, note the `Refer-To` SIP header.

![referto-bad-uri](https://user-images.githubusercontent.com/197660/90315051-2a472d80-df10-11ea-9aed-cb31cca21c40.png)

**Comment by thornzz** [comment]
You are life saver. Thank you so much. 👍

**Comment by jafarulla15** [comment]
![image](https://user-images.githubusercontent.com/15998911/121058920-b51c5000-c7e2-11eb-8fd0-286ad63526b8.png)
,
I am sorry for bothering you. I am very beginner and try to test the call transfer and fail. Don't know why. Tried from softphone at example and also from the console. Would you please help me find out what are the wrong. 
Best Regards
