### ISSUE TITLE
Question raw h264 nal packets

### ISSUE THREAD

**Issue by Terricide** [sipsorcery/sipsorcery#289]
I have an app that generates raw h264 packets and I've been passing them over websocket/data channels and using some javascript to render in the browser. I'm trying to figure out how to get them into a video stream. Right now I'm a little stuck on getting it into SendMedia in the right way.

**Comment by sipsorcery** [comment]
Do you mean how should you pass your H264 packets to the `RTCPeerConnection` as a video stream?

If so the [WebRTCTestPatternServer example](https://github.com/sipsorcery/sipsorcery/blob/master/examples/WebRTCExamples/WebRTCTestPatternServer/Program.cs) should be very close to what you're after.

The example is using VP8 but you can throw away the methods generating and encoding the test pattern since you've already got an H264 stream.

The main points are:

 - Add the media stream:

````
MediaStreamTrack videoTrack = new MediaStreamTrack(SDPMediaTypesEnum.video, false, new List<SDPMediaFormat> { new SDPMediaFormat(SDPMediaFormatsEnum.H264) }, MediaStreamStatusEnum.SendOnly);
pc.addTrack(videoTrack);
````

 - Once connected start sending the video packets:

````
pc.SendMedia(SDPMediaTypesEnum.video, H264_TIMESTAMP_SPACING, h264EncodedBuffer);
````

It should be a lot easier sending a video stream directly over RTP compared to using a data channel.

**Comment by Terricide** [comment]
That is actually what I was thinking when I was looking through the samples. I'll put together an h264 sample that you can use and test with.

**Comment by Terricide** [comment]
Here is a sample that switches from vp8 to h264
[SampleH264Streaming.zip](https://github.com/sipsorcery/sipsorcery/files/5077871/SampleH264Streaming.zip)

**Comment by sipsorcery** [comment]
Very nice, thanks!

If you don't mind I'll add the OpenH264 wrapper to the `SIPSorceryMedia` project?

If you ever come across a H264 or VPX encoder that's been ported to C# it'd be great to be able include it and not have to worry about distributing native dll's.

**Comment by Terricide** [comment]
I don't mind at all :) I'm always keeping an eye out for H264 or VPX encoders for c# as I would love to find something as well.

I found this h264 encoder last night
https://github.com/ngraziano/SharpRTSP/tree/master/RtspCameraExample

However it does zero compression so not really useful for any of my purposes.

Also if you include it you would probably want to not include openh264-2.0.0-win32.dll in the library though and download it directly from cisco's website because if you do they cover all the licensing stuff.

http://ciscobinary.openh264.org/openh264-2.0.0-win32.dll.bz2

**Comment by Terricide** [comment]
I was thinking about trying to use something like 
https://www.nuget.org/packages/Wasmtime and trying to the ffmpeg library (https://github.com/BrianJFeldman/ffmpeg.js.wasm) or vpx library (https://github.com/GoogleChromeLabs/webm-wasm) ports to run because then it would be cross platform and be running safe code in a sandbox.

**Comment by sipsorcery** [comment]
> I found this h264 encoder last night https://github.com/ngraziano/SharpRTSP/tree/master/RtspCameraExample

It'd be nice to have something like that just so that WebRTC examples could run cross platform without having to install any additional libraries. I wonder if the simple H264 encoder would even work given it doesn't adhere to a standard [h264 profile[(https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles). I'll try it out but am not too hopeful.

I came across a partial C# port of libvpx, https://github.com/honzasp/vp8l, but it didn't work OOB and I didn't dig into it.

> I was thinking about trying to use something like https://www.nuget.org/packages/Wasmtime...

That's interesting, I hadn't thought of that. I've heard Zoom use WASM based encoding in the browser in their products so it seems it could be perform well enough.

**Comment by Terricide** [comment]
This library says it converts wasm to il

https://github.com/RyanLamansky/dotnet-webassembly

**Comment by Terricide** [comment]
Wasmer is the only one I could get to partially work so far but you have to define like 40 external functions for it to call.

**Comment by sipsorcery** [comment]
Hmm doesn't sound like much fun, Personally I think I'd look at porting [libvpx](https://github.com/webmproject/libvpx) to C# ahead of WASM.

**Comment by Terricide** [comment]
Yeah I guess I figured if I could get wasm to work then any future library could work. 

https://github.com/RyanLamansky/dotnet-webassembly/issues/24

**Comment by Terricide** [comment]
Just curious the sample SampleH264Streaming.zip didn't work for you right? I'm guessing something in the RTP stream needs to be modified.

**Comment by sipsorcery** [comment]
@Terricide you've already spotted it and the new approach for PInvoking native library codecs is demonstrated in [SIPSorceryMedia.Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows). I did add your [OpenH264Encoder](https://github.com/sipsorcery/SIPSorceryMedia.Windows/blob/master/src/codecs/OpenH264Encoder.cs) class but encountered some difficulties wiring it up and didn't spend too much time on it.

I did spend two days sorting out the [RTP packetisation for H264 NALs](https://github.com/sipsorcery/sipsorcery/blob/89d9b20337afa583c2d08677630ca9babcfb129c/src/net/RTP/RTPSession.cs#L1619) and was able to successfully send H264 packets using an [FFmpeg integration](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg) (which is still a work in progress).

I'll close this issue for now. If there are specific issues/requests with any of the above new issues can be opened. I'll probably get around to doing a PInvoke layer for a H264 library eventually, if you don't beat me to it. In the shorter term I'll be looking at the FFmpeg integration.

**Comment by Terricide** [comment]
Sounds great, thanks for the help. Ill see what I can do with helping you wire up OpenH264. The nice thing about having both ffmpeg and OpenH264 is that you can use ffmpeg LPGL that is missing software h264 encoding and use OpenH264 to fill in that gap.
