### ISSUE TITLE
Double SIP messages

### ISSUE THREAD

**Issue by bakycar** [sipsorcery/sipsorcery#29]
Dear SIPSorcery team!

As I am implementing a hold/unold feature in the softphone project I have noticed, while using WireShark, that all SIP packets get sent twice. They have the same CSeq and do not seem to bother the PBX but it seems like this is not something that should be good practice.

We have not updated the repository in a while so I was just wondering wether or not You have already found a solution for this and if we should start merging to resolve this issue.

The second problem is that when a "reliable" message is sent (especially the ReINVITE which we ar eusing for holding and unholding a call) the SoftPhone does not stop sending it in the "reliable" thread, we have already found a work around for this but just wanted to inform You of the issue.

The last issue is that when we create a hold with the ReINVITE we don't seem to be able to get any other calls from the PBX, while doing it on another client this seems to work fine, so we were also wondering if You had any insight as to why this might be happening. Are we missing a header or SDP parameter int he ReINVITE? We have tried copying the SDP sent from antoher client but even while all of the parameters are synchronized this still seems not to work as it should.

We thank You for Your help!

With kind regards, Urban.

**Comment by sipsorcery** [comment]
SIP requests (and INVITE responses) will get resent if the response (or ACK request) is not received within 500ms. If the PBX is a bit slow or it's a long way away from a network point of view then a retransmit is to be expected. They are part of the SIP standard and normal behaviour.

The retransmit thread should stop sending any single message after 32s or eleven retries. Are you seeing it go on for longer than that? If so that's a bug.

Generally a call hold re-INVITE request repeats the same SDP that was used except that it modifies the a=active, a=recvonly or a=sednonly attribute (see https://tools.ietf.org/html/rfc7088). You do need to change the CSeq and some other headers in the SIP re-INVITE request but the sipsorcery stack should do that for you. Either way there shouldn't be a way one call can affect the way the PBX routes any other call. If you can capture a SIP trace then feel free to email it to me at aaron@sipsorcery.com and I'll take a look.

**Comment by sipsorcery** [comment]
If there's further info on this issue feel free to re-open.
