### ISSUE TITLE
TLS-PSK 

### ISSUE THREAD

**Issue by Educsys** [sipsorcery/sipsorcery#292]
Good day, Aaron. As part of the project,  i need  the TLS channel based on the client and server certificates, working as a client and based on the shared tls-psk key. Can I do this?

**Comment by sipsorcery** [comment]
It doesn't look like Chrome support TLS-PSK so the answer is most likely no you won't be able to use it with WebRTC.

![chrome_cipher_suites](https://user-images.githubusercontent.com/197660/90607525-3cb7b480-e1f9-11ea-890a-7c66dae1f783.png)

If you can find info indicating otherwise we may be able to support it since in theory it should just be a matter of adding an extra option to the `BouncyCastle` configuration.

You can definitely specify your own certificate and private key to use. The private key doesn't get used directly and is instead used in a `Diffie-Hellman` exchange ann after that a further AES key is derived as the encryption key for the SRTP packets.

You may also be interested in [WebRTC Insertable Streams](https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/).

**Comment by Educsys** [comment]
Most likely, there was an inaccuracy in the translation into English. There is no need to support chrome. Now I use siptransport tcp, but the system I connect to in one module requires tls based on the server certificate, and the other module requires tls-psk.

**Comment by sipsorcery** [comment]
Ah you mean for SIP not WebRTC.

The [SIPTLSChannel](https://github.com/sipsorcery/sipsorcery/blob/master/src/core/SIP/Channels/SIPTLSChannel.cs) uses the .NET/.NET Core `SslStream` for TLS. You would need to check is `SslStream` supports `TLS-PSK`.
