### ISSUE TITLE
SoftPhone - Answer Call using AudioSource = AudioSourcesEnum.Silence results in random noise

### ISSUE THREAD

**Issue by FrankPfattheicher** [sipsorcery/sipsorcery#297]

**Comment by FrankPfattheicher** [comment]
Recording atteched

**Comment by sipsorcery** [comment]
Attachment is missing.

**Comment by FrankPfattheicher** [comment]
[Recording.zip](https://github.com/sipsorcery/sipsorcery/files/5125692/Recording.zip)

Ah - it does not sullort aac atachements :-/

**Comment by sipsorcery** [comment]
I've attempted to replicate this issue but have been unsuccessful.

I have two suspicions as to what could be the cause:

 - 1. If two audio sources are active at the same time it can result in static on the receiver. I have had cases in the past where calling `_waveInEvent?.StopRecording();` to stop the input from the microphone has not worked and samples continue to get generated. In your case if you're answering immediately with silence the microphone should never be activated but perhaps something is going wrong,

 - 2. If the codecs on the send and receiver are mismatched the the silence packets could generate static on the receiver.

The easiest way to identify if one of these cases could be the problem is to do a wireshark capture of the SIP and RTP packets on a call. You can use the wireshark capture filter below on the machine running the softphone to get the required packets:

`udp port 5060 or udp portrange 49000-65535`

**Comment by sipsorcery** [comment]
Feel free to re-open if there's any further info.
