### ISSUE TITLE
m_udpSocket.BeginReceiveMessageFrom : System.NotImplementedException in Xamarin.Android

### ISSUE THREAD

**Issue by dxmann** [sipsorcery/sipsorcery#302]
Hello!
I'm testing the sip client on Android.
I've found the exception in `System.NotImplementedException: The method or operation is not implemented.` in:
- SIPUDPChannel.cs:97
- SIPUDPChannel.cs:122

Replacing the BeginReceiveMessageFrom with BeginReceive and EndReceiveMessageFrom with EndReceive I have no errors.

My partial impementation is:
```
private void Receive()
{
    try
    {
        //EndPoint recvEndPoint = (ListeningIPAddress.AddressFamily == AddressFamily.InterNetwork) ? new IPEndPoint(IPAddress.Any, 0) : new IPEndPoint(IPAddress.IPv6Any, 0);
        //m_udpSocket.BeginReceiveMessageFrom(m_recvBuffer, 0, m_recvBuffer.Length, SocketFlags.None, ref recvEndPoint, EndReceiveMessageFrom, null);
        m_udpSocket.BeginReceive(m_recvBuffer, 0, m_recvBuffer.Length, SocketFlags.None, EndReceiveMessageFrom, null);
    }
    catch (ObjectDisposedException) { } // Thrown when socket is closed. Can be safely ignored.
    catch (Exception excp)
    {
        // From https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3056
        // the BeginReceiveMessageFrom will only throw if there is an problem with the arguments or the socket has been disposed of. In that
        // case the socket can be considered to be unusable and there's no point trying another receive.
        logger.LogError($"Exception Receive. {excp.Message}");
        logger.LogDebug($"SIPUDPChannel socket on {ListeningEndPoint} listening halted.");
        Closed = true;
     }
}

private void EndReceiveMessageFrom(IAsyncResult ar)
{
    EndPoint remoteEP = (ListeningIPAddress.AddressFamily == AddressFamily.InterNetwork) ? new IPEndPoint(IPAddress.Any, 0) : new IPEndPoint(IPAddress.IPv6Any, 0);

    try
    {
        if (!Closed)
        {
            SocketFlags flags = SocketFlags.None;
             //int bytesRead = m_udpSocket.EndReceiveMessageFrom(ar, ref flags, ref remoteEP, out var packetInfo);
            int bytesRead = m_udpSocket.EndReceive(ar);
            //var remoteE = m_udpSocket.RemoteEndPoint as IPEndPoint; // gives an exception
            var localE = m_udpSocket.LocalEndPoint as IPEndPoint;
            if (flags == SocketFlags.Truncated)
             {
                 logger.LogWarning($"The message was too large to fit into the specified buffer and was truncated.");
             }

             if (bytesRead > 0)
             {
                 SIPEndPoint remoteEndPoint = new SIPEndPoint(SIPProtocolsEnum.udp, remoteEP as IPEndPoint, ID, null);
                 SIPEndPoint localEndPoint = new SIPEndPoint(SIPProtocolsEnum.udp, localE/*new IPEndPoint(packetInfo.Address, Port)*/, ID, null);
                 byte[] sipMsgBuffer = new byte[bytesRead];
                 Buffer.BlockCopy(m_recvBuffer, 0, sipMsgBuffer, 0, bytesRead);
                 SIPMessageReceived?.Invoke(this, localEndPoint, remoteEndPoint, sipMsgBuffer);
             }
         }
     }
     catch (SocketException sockExcp)
     {
         // This exception can occur as the result of a Send operation. It's caused by an ICMP packet from a remote host
         // rejecting an incoming UDP packet. If that happens we want to stop further sends to the socket for a short period.
         logger.LogWarning($"SocketException SIPUDPChannel EndReceiveMessageFrom from {remoteEP} ({sockExcp.ErrorCode}). {sockExcp.Message}");
         if (remoteEP != null)
             m_sendFailures.TryAdd(remoteEP as IPEndPoint, DateTime.Now);
    }
    catch (ObjectDisposedException) { }// Thrown when socket is closed. Can be safely ignored.
    catch (Exception excp)
    {
        logger.LogError($"Exception SIPUDPChannel EndReceiveMessageFrom. {excp.Message}");
    }
    finally
    {
        if (!Closed)
            Receive();
    }
}
```

The above implementation is not equivalent, so pay attenction! :)

**Comment by sipsorcery** [comment]
Thanks for the info. Did this happen in an emulator or on an Android device? I have run a [test application](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/XamarinDataChannelTest) in the emulator and not come across this.

The dilemma with switching to `BeginReceive` is that determining the remote end point for a UDP receive is no longer possible. That means for VoIP situations the RTP end point must match exactly the one specified in the SDP. This will generally be fine if only communication with servers on public IP addresses but won't work so well if attempting to communicate with other clients on private IP addresses where NATs are involved.

There will also be another set of problems with WebRTC and attempting to match and create ICE candidates.

**Comment by dxmann** [comment]
I've encountered this problem on a Samsung A51 with Android 10

**Comment by neminush** [comment]
I confirm that there is a problem in 'SIPUDPChannel'. The problem is reproducible on Android and highly likely on iOS too. At least in iOS 'SIPRegistrationUserAgent' doesn't work either.

![System NotImplementedException in Xamarin](https://user-images.githubusercontent.com/33318899/95792131-84375a00-0ceb-11eb-8ff1-d30be511abef.png)

`{System.NotImplementedException: The method or operation is not implemented.
  at System.Net.Sockets.Socket.BeginReceiveMessageFrom (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint& remoteEP, System.AsyncCallback callback, System.Object state) [0x00026] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/System.Net.Sockets/Socket.cs:1934 
  at SIPSorcery.SIP.SIPUDPChannel.Receive () [0x00029] in ...\SIPSorcery\core\SIP\Channels\SIPUDPChannel.cs:97 }
    base: {System.SystemException}`

I think any Visual Studio Emulator for Android can reproduce the problem.

![vs em for android](https://user-images.githubusercontent.com/33318899/95792606-89e16f80-0cec-11eb-90f1-efee72d50262.png)

**Comment by sipsorcery** [comment]
That's very helpful, thanks. Will try a test with Xamarin Forms pronto.

**Comment by neminush** [comment]
I should note that the implementation of the 'SIPUDPChannel' class in SIPSorcery 3.6.0 works fine on mobile devices.

**Comment by neminush** [comment]
What if we will use 'BeginReceiveFrom' instead of 'BeginReceiveMessageFrom' ?

I checked the 'BeginReceiveFrom' and 'EndReceiveFrom' methods - they works fine in both iOS and Android.

Look what I did:

![BeginReceiveFrom-example](https://user-images.githubusercontent.com/33318899/95861164-c0a99b00-0d69-11eb-837a-67e29ccd1446.png)

**Comment by sipsorcery** [comment]
As background to this issue the reason to use `Begin/EndMessageReceiveFrom` is, as mentioned in the comments (and alluded to above), to get the `IPPacketInformation` from `m_udpSocket.EndReceiveMessageFrom`.

The reason the `IPPacketInformation` is needed is that when a SIP channel is listening on `IPAddress.Any` it has no way of knowing which of it's IP addresses a SIP message was received on. For SIP operation it's crucial to know this as the critical headers require the local IP address to be set.

Some of the choices are:

 - Don't use `IPAddress.Any` and force the application to choose the specific IP addresses to listen on. This is a big pain for applications running on OS with multiple IP addresses, which is pretty much every desktop OS these days.

 - Pick one IP address, typically the Internet accessible one, to use for the return address on `IPAddress.Any` sockets. This will break any SIP packets sent between hosts on private networks. Big pain.

 - Add a new socket check along the lines of the existing [NetServices.DoCheckSupportsDualModeIPv4PacketInfo](https://github.com/sipsorcery/sipsorcery/blob/acf42d859d530e91b45b29cbd3c0afaa0476a485/src/sys/Net/NetServices.cs#L433) but for IPv4 only sockets. If PacketInfo is not supported then use the `Begin\EndReceiveFrom` methods instead of `Begin/EndMessageReceiveFrom`. But what to do about determining the local IP address a UDP packet was received on?

I'm still thinking of a solution but any suggestions are welcome.

**Comment by neminush** [comment]
I'm thinking too and collecting information... I'll answer later.
