### ISSUE TITLE
_lookupClient.QueryAsync(host, QueryType.A, QueryClass.IN, ct) returns CNAME

### ISSUE THREAD

**Issue by raphaotten** [sipsorcery/sipsorcery#303]
I had a problem with the DNS lookup.
It turned out the problem came from 
`_lookupClient.QueryAsync(host, QueryType.A, QueryClass.IN, ct) `
(line 348 in SIPDns.cs) which returned a CNAME for the given host.
I changed line 353 to
`result = GetFromLookupResult(uri.Protocol, aResult.Answers.Where(x=>x.RecordType ==ResourceRecordType.A).First(), port);
`
and now everything works fine.

**Comment by raphaotten** [comment]
seems like
`aResult.Answers.ARecords().First() 
`is the clean way (also done this way in the example here: [https://dnsclient.michaco.net/docs/DnsClient.LookupClient.html](https://dnsclient.michaco.net/docs/DnsClient.LookupClient.html) )
`aResult.Answers.AaaaRecords().First() 
`for line 328

the >0 check before similar in both cases

**Comment by raphaotten** [comment]
Could you integrate it in a release? Or can't you confirm it?

**Comment by sipsorcery** [comment]
I hadn't checked it because for some reason I'd assumed this was an Android specific issue and I don't have a device. But looking at it again I can't see Android mentioned anywhere so seems I've got my wires crossed.

Can you let me know the hostname lookup that returns the CNAME result? I'll verify and add a unit test. If it all looks good I can do a release with this fix.

**Comment by sipsorcery** [comment]
Fixed and released in nuget package `v4.0.81-pre`. Apols for the initial confusion.

**Comment by raphaotten** [comment]
Thank you.
I think it's mixed up a bit now though:

I think line 353 should be
`result = GetFromLookupResult(uri.Protocol, aResult.Answers.ARecords().First(), port);// not AaaaRecords().First()`
and line 328 should have AaaaRecords().First()

**Comment by sipsorcery** [comment]
I decided to use `AddressRecords` instead of `ARecords` and `AaaaRecords`. If a `CNAME` record resolves to an IPv6 only host then may as well at least return that to the application to try and use.

[Line 353](https://github.com/sipsorcery/sipsorcery/blob/fb700a2c7d9a385415a933b849e329fafdd1b017/src/core/DNS/SIPDns.cs#L353) is:
`result = GetFromLookupResult(uri.Protocol, aResult.Answers.AddressRecords().First(), port);`

I missed line 328, thanks for pointing that out. I'll add an `AddressRecords` call there as well.

**Comment by sipsorcery** [comment]
Closing as fixed.
