### ISSUE TITLE
UACInviteTransaction constructor not accessible outside of the SipSorcery assembly

### ISSUE THREAD

**Issue by Jer-Wom** [sipsorcery/sipsorcery#337]
Hello,

Why "UACInviteTransaction" contructor is "internal" instead of "public" ? This prevents to create an INVITE transaction outside of the SipSorcery assembly. 
Is it on purpose or is it a mistake ? Can you make this constructor public like for "UASInviteTransaction" ? 

If it's on puprose, how should I create an INVITE transaction without using SIPClientUserAgent or SIPUserAgent classes ?

Thanks for your help

**Comment by sipsorcery** [comment]
It's `internal` because I couldn't think of a situation where an application would want to use `UACInviteTransaction` instead of [SIPClientUserAgent](https://github.com/sipsorcery/sipsorcery/blob/master/src/app/SIPUserAgents/SIPClientUserAgent.cs).

If you were to use `UACInviteTransaction`  directly you have to do extra work such as creating the `INVITE` request, handling cancellations etc. Do you want to handle those operations manually?

**Comment by Jer-Wom** [comment]
Yes. I will have to interface with a product that uses the SIP protocol in a very unconventional way. A lot of proprietary headers and indialog SIP messages are used (like sip INFO). 
Handling all these messages without easily having access to the lower layer will probably be painful and difficult to maintain in the long run.

**Comment by sipsorcery** [comment]
OK fair enough. I've made the constructor public on `master`. It will be available in the next nuget package > `4.0.85-pre`.

**Comment by Jer-Wom** [comment]
Ok, thanks for your help
