### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#34]
Hey Aaron,
I did a lot of work regarding IPV6 in SIPSorcery (parsing, formatting, DNS Resolution)
but only in the 4 libraries i am really using: Core, App, Sys, Net
Before creating a pull request, i wanted to let you know and ask if, by any chance, you did any work for IPv6 yourselves?
And because I did a lot of customization in other places too, merging the code is much work.
So please let me know if you have any interest in my source codes.

Ralf

**Comment by sipsorcery** [comment]
Hi Ralf,

I haven't done any IPv6 work and I'd be very keen to see what you've come up with. I know it's extra work but is it possible for you to do a pull request just with the IPv6 changes?

I'm nervous about your current pull requests because they touch so many parts of the code and I'm afraid I'll miss something and only discover a problem after a deployment. If the pull requests are single purpose commits it makes it a lot easier to check and get comfortable with it.

Thanks,
Aaron

**Comment by sipsorcery** [comment]
IPv6 is now supported.
