### ISSUE TITLE
WebRTC client for desktop app

### ISSUE THREAD

**Issue by jafarulla15** [sipsorcery/sipsorcery#347]
At first I want to give you thanks that your work just save my a lots of time. I am trying to develop a client app which is both desktop and web application, want to connect with sip client. WebRTC client is working fine with sip, But I need a desktop app client. Can you give me some direction to create a desktop client app which will use web socket and connect with webRTC server as like web client doing 
or are you creating any like this?

Best Regards

**Comment by sipsorcery** [comment]
> Can you give me some direction to create a desktop client app which will use web socket and connect with webRTC server as like web client doing

You want a desktop WebRTC client that connects to your server application and uses Web Sockets for signalling?

If so there are numerous [WebRTC Examples](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples) that are doing exactly that. As a starting point see [WebRTCClient](https://github.com/sipsorcery/sipsorcery/blob/master/examples/WebRTCExamples/WebRTCClient/Program.cs). They are all console applications rather than Desktop GUI applications but that is only a small adjustment.

**Comment by jafarulla15** [comment]
Sorry for late response and thanks for your time.
I have tried to run and connect WebRTCClient with server: WebRTCTestPatternServer. But didn't success in making connection. Would you please give me some instruction so that I can run it successfully and connect with server.

and also I found that here client is using http, not ws. Is it possible to make a desktop app client that use ws not http. As it's very easy to understand.

Best Regards

**Comment by jafarulla15** [comment]
![image](https://user-images.githubusercontent.com/15998911/98830788-0048cd00-2465-11eb-9026-9560cc3751b8.png)

When running getting this messages. Please need help.

**Comment by sipsorcery** [comment]
There are some instructions [here](https://github.com/sipsorcery/sipsorcery/tree/master/examples/webrtccmdline#node-dss) about how to use [node-dss](https://github.com/bengreenier/node-dss). Do note `node-dss` is a very very basic HTTP server based on node.js that's being used in the demo programs for convenience. In a real application you'll most likely want to replace it with a more sophisticated signaling solution.

**Comment by sipsorcery** [comment]
Closing for now. Feel free to re-open if any additional questions.
