### ISSUE TITLE
Android WebRTC Native Compatability

### ISSUE THREAD

**Issue by alextatham** [sipsorcery/sipsorcery#355]
Hello,

I'm working with this library and a WebRTC implementation using native Android libraries.

I have two Android devices that can call ok between them.  I'm now trying to use this stack to connect to them from Windows using a c# app.  Quite a lot more testing to do but I thought I'd share the current status for any pointers.  :)

I have the following things I'm looking at...

1. The stun negotiation fails unless the candidates are manipulated in transit.  If I only include candidates I know will work (for example removing all the loopback options), it does work but logs STUN messages every x seconds as if something is still thinking about it.  Sorry I don't know how to say that better.  I do have packet captures to work through yet.
2. The video is upside down and green when rendered in Android.
3. I have the microphone shacking issue in Windows 10 which I'll re-open from April and focus on.
4. I can't get the video to render from Android back to Windows 10 but I haven't actually tried much to fix that.
5. The audio is delayed by about  6 seconds and often breaks up.

Not enough detail here I know but I'll continue to work through each item...

**Comment by sipsorcery** [comment]
I'm more than happy to help where I can with Android (and iOS) apps. From a personal point of view I'd like to get more exposure to both platforms. I have an Android phone (still in the box) waiting for me to do some testing on.

In this case it sounds like you're using a native WebRTC library for your Android app? Is it `libwebrtc`? And for the Windows portion of your app you are using this sipsorcery library?

> 1. The stun negotiation fails unless the candidates are manipulated in transit. If I only include candidates I know will work (for example removing all the loopback options), it does work but logs STUN messages every x seconds as if something is still thinking about it. Sorry I don't know how to say that better. I do have packet captures to work through yet.

That's a bug somewhere. Can you provide examples of the problem ICE candidates.

The [ICE RFC](https://tools.ietf.org/html/rfc8445#section-5.1.1.1) does state that loopback addresses should not be used in ICE candidates but I can understand where they might be included for debug or testing purposes. Either way the sipsorcery library should cope with them.

> it does work but logs STUN messages every x seconds as if something is still thinking about it

Once an ICE connection is established STUN messages will still be sent to monitor for connection failures.

> The video is upside down and green when rendered in Android.

That could be a problem with the Android library. Are you able to test it with a web browser on Windows or does your app only run as a standalone .NET app?

> I have the microphone shacking issue in Windows 10 which I'll re-open from April and focus on.

Any additional info about that issue is welcome. I've still never come across it. It may be related to a particular type of audio device.

> I can't get the video to render from Android back to Windows 10 but I haven't actually tried much to fix that.

Again could be an issue with the Android library.

> The audio is delayed by about 6 seconds and often breaks up.

On one or both peers? If the audio source is from your .NET application is your CPU utilisation low?

If your Android app is something that can be shared and easily deployed I'm happy to run some tests.

**Comment by sipsorcery** [comment]
Closing for now pending any further info (some issues were dealt with out-of-band).
