### ISSUE TITLE
m=application in SDP

### ISSUE THREAD

**Issue by Educsys** [sipsorcery/sipsorcery#358]
Good afternoon. In rtpsession.addtrack, i can create a MediaStreamTrack with SDPMediaTypesEnum.application. this is necessary for RTCP management to go through a separate channel. But when creating a session and adding an app channel, there is no created element in the sdp offer. Please help me, add this element.

```
var rtpSession = new RTPSession(true, false, false, IPAddress.Any);
rtpSession.addTrack(new MediaStreamTrack(SDPMediaTypesEnum.audio, false, new List<SDPAudioVideoMediaFormat>()
{
	new SDPAudioVideoMediaFormat(SDPWellKnownMediaFormatsEnum.PCMU)
}));
rtpSession.addTrack(new MediaStreamTrack(SDPMediaTypesEnum.application, false, new List<SDPAudioVideoMediaFormat>()
{
	new SDPAudioVideoMediaFormat(SDPWellKnownMediaFormatsEnum.PCMU) // what is needed here?
}));
```

I need something similar:

```
m=audio 55316 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=label:1
i=speech
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
a=sendrecv
m=application 55317 udp MCPTT
a=fmtp:MCPTT mc_queueing;mc_priority=4
```
But i get:
```
v=0
o=- 1491952031 0 IN IP4 127.0.0.1
s=-
c=IN IP4 127.0.0.1
t=0 0
m=audio 53088 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
```

Thank you.

**Comment by sipsorcery** [comment]
There's no logic in `RTPSession` that allows anything but `audio` or `video` tracks. The only exception is to add an `application` announcement for for WebRTC data channels, see [here](https://github.com/sipsorcery/sipsorcery/blob/91fd39ac9a2d6a01b5d20e5b9830750339e79f50/src/net/WebRTC/RTCPeerConnection.cs#L1011).

Is the idea that your application will handle the `MCPTT` packets?

**Comment by Educsys** [comment]
Yes, I need to try to get rtp packets from the stream and learn how to send and receive rtcp packets

**Comment by sipsorcery** [comment]
> Yes

Ok I can add an enhancement issue to allow custom SDP `application` announcements to be added. Be aware that once the ability is added the sipsorcery library won't be able to understand or negotiate custom `application` announcements so it will be up to your application to deal with any format negotiations etc.

> I need to try to get rtp packets from the stream

[RTPSession.OnRtpPacketReceived](https://github.com/sipsorcery/sipsorcery/blob/91fd39ac9a2d6a01b5d20e5b9830750339e79f50/src/net/RTP/RTPSession.cs#L322) provides access to all RTP packets. 

> learn how to send and receive rtcp packets

Currently there is [RTPSession.SendRtcpFeedback](https://github.com/sipsorcery/sipsorcery/blob/91fd39ac9a2d6a01b5d20e5b9830750339e79f50/src/net/RTP/RTPSession.cs#L1799) which allows an application to send custom `RTCP` feedback reports.

If that's not enough I could make [RTPSession.SendRtcpReport](https://github.com/sipsorcery/sipsorcery/blob/91fd39ac9a2d6a01b5d20e5b9830750339e79f50/src/net/RTP/RTPSession.cs#L2311) public BUT it's unusual for an application to need to send RTCP reports manually. What's the use case?

**Comment by Educsys** [comment]
Responded to an email with examples and descriptions

**Comment by sipsorcery** [comment]
Is this the specification for what you're implementing: [Mission Critical Push To Talk (MCPTT) media plane control; Protocol specification](https://www.etsi.org/deliver/etsi_ts/124300_124399/124380/13.00.02_60/ts_124380v130002p.pdf)?

If so that's going to need a lot more than the ability to set an SDP `application` announcement and send RTCP packets. I scanned the whole specification but didn't get a clear idea of the SIP flows required so I'm not sure how complicated they are. What was apparent was the number and detail of new RTCP report types required. RTCP is the main control mechanism used in the specification. But I'll assume you're already aware of all that.

Before even looking at the spec I'd thought about this some more and I'd come to the conclusion that adding application specific features to the `RTPSession` class is not the best approach. Instead it would be better to sub class and adjust the areas where new features are required. This is the same approach I used for the `RTCPeerConnection` class which essentially adds WebRTC features to `RTPSession`.

For `MCPTT` one thing that did stick out from my brief look at the spec was:

> 4.3.3 Establishing a media plane control channel
> 4.3.3.1 General
>
> <snip>
> 
> The port used for RTCP messages associated with the media plane control channel shall be different than ports used for
RTCP messages associated with other "m=" lines (e.g. RTP) in the SDP.
NOTE 1: As RTCP is used to transport messages on the media plane control channel, the "m=" line port value
indicates an RTCP port. This is different from cases where an "m=" line is associated with an RTP-based
stream, and the "m=" line port value indicates an RTP port.
NOTE 2: In case the media plane control channel uses a different IP address than other media described in the SDP,
a media plane control channel specific "c=" line also needs to be associated with the "m=" line associated
with the media plane control channel.
The format of the optional SDP fmtp attribute, when associated with the media plane control channel, is described in
clause 12.
The example below shows an SDP media description for a media plane control channel. 

Which is saying that the RTCP connection used is different to the one used for the RTP audio RTCP reports. It's not that difficult to create a new RTCP connection but the `RTPSession` class does not do so as it's not required for SIP or WebRTC applications.

I can probably help a bit to get you started by creating a new class such as `McpttRtpSession` as a sub class of `RTPSession` and add the SDP change. But after that you'd still have a LOT of work to do. Are you sure you want to implement this protocol almost from scratch? It seems a BIG job.

**Comment by Educsys** [comment]
Creating an McpttRtpSession with additional channels for rtcp transmission is a good option. It would help me a lot to move in this direction. Fortunately, I need to implement a small part of the mcptt and using your library already allows me to solve a lot of problems.

**Comment by sipsorcery** [comment]
Here's an example of a `RTPSession` sub-class you could use as a starting point. Note that an additional `RTPChannel` is created to send the MCPTT RTCP reports on. It will be used for RTCP only, no RTP packets need to be sent on it.

```csharp
using System.Net;
using System.Threading.Tasks;
using SIPSorcery.Net;

namespace demo
{
    public class McpttRtpSession : RTPSession
    {
        private RTPChannel _mcpttRtpChannel;

        public SDPMediaAnnouncement McpttAnnouncement { get; set; }

        public McpttRtpSession() 
            : base(true, false, false)
        {
            _mcpttRtpChannel = new RTPChannel(false, null);
        }

        public override SDP CreateAnswer(IPAddress connectionAddress)
        {
            var sdp = base.CreateAnswer(connectionAddress);
            AddMcpttAnnouncementToSDP(sdp);
            return sdp;
        }

        public override SDP CreateOffer(IPAddress connectionAddress)
        {
            var sdp = base.CreateOffer(connectionAddress);
            AddMcpttAnnouncementToSDP(sdp);
            return sdp;
        }

        public override Task Start()
        {
            _mcpttRtpChannel.Start();
            return base.Start();
        }

        public override void Close(string reason)
        {
            _mcpttRtpChannel.Close(reason);
            base.Close(reason);
        }

        public void SendMcpttRtcpReport(RTCPSDesReport rtcpReport, IPEndPoint remoteEP)
        {
            byte[] buffer = rtcpReport.GetBytes();
            _mcpttRtpChannel.Send(RTPChannelSocketsEnum.RTP, remoteEP, buffer);
        }

        private void AddMcpttAnnouncementToSDP(SDP sdp)
        {
            if(McpttAnnouncement != null)
            {
                sdp.Media.Add(McpttAnnouncement);
            }
        }
    }
}
```

**Comment by Educsys** [comment]
It looks great. I have a couple of questions. Will the onrtppacketreceived handler receive packets? In SDPMediaAnnouncement, I can't get only a string containing fmtp, without setting Rtpmap to a non-null value. Also would like to be able to not set the a=sendrecv parameter

**Comment by sipsorcery** [comment]
> Will the onrtppacketreceived handler receive packets?

Yes.

> In SDPMediaAnnouncement, I can't get only a string containing fmtp.

There was a bug setting `fmtp` attributes on `SDPApplicationMediaFormat` instances. It's fixed on `master` now.

> Also would like to be able to not set the a=sendrecv parameter

I've adjusted the SDP logic so that the media stream status parameter is optional. Also now on `master`.

**Comment by Educsys** [comment]
I checked that SDP are now being created correctly. What actions do I need to take to successfully create an mcptt session?

**Comment by sipsorcery** [comment]
>  What actions do I need to take to successfully create an mcptt session?

Do you mean how do you use something like the `McpttRtpSession` class shown above and that you have added all the logic for? If so you can pass it into the `SIPUserAgent` class when placing a call.

```csharp
var mcptt = new McpttRtpSession();
var callTask = userAgent.Call(DESTINATION, null, null, mcptt);
```

**Comment by Educsys** [comment]
Perhaps it is lost in translation. I meant, will you add the mcpttsession class to nuget, or will I need to implement it as shown in the example? I can't implement it right now, because the _mcpttRtpChannel.Send from the example is an internal method. At the moment, I use the library via nuget, and there are no changes to SDPMediaAnnouncement. I apologize for the slight misunderstanding

**Comment by sipsorcery** [comment]
> I meant, will you add the mcpttsession class to nuget, or will I need to implement it as shown in the example?

You will need to implement it.

>  I can't implement it right now, because the _mcpttRtpChannel.Send from the example is an internal method. At the moment, I use the library via nuget, and there are no changes to SDPMediaAnnouncement.

There are existing Send methods on the base `RTPSession` class you should be able to use instead of `RtpChannel.Send`. And yes  if you need the very latest fixes you'll generally need to checkout and use the `master` branch directly instead of the nuget package.

**Comment by Educsys** [comment]
Thank you so much for your help, your library is very helpful in solving a lot of problems. I will now begin this task. At this point, I will close the issue so that it doesn't hang in the open state.

**Comment by Vinniento** [comment]
I am currently facing the exact same problem and wanted to ask, if the SipSorcery lib has been adapted in any way since this post to incorporate a second "m=" line @sipsorcery?

I would need it to get the MCPTT floor control information, which is sent over an additional RTCP channel.
