### ISSUE TITLE
Softphone 2016 issues readme

### ISSUE THREAD

**Issue by Devinete** [sipsorcery/sipsorcery#369]
Hello there.
Are the following issues still valid on the library?
Isn't support for other codecs now allowed ?

Audio:
------

The bad news is that the softphone is barely usable due to the inability of .Net to
reliably deliver audio samples from the microphone. What tends to happen is that as 
soon as incoming RTP packets start arriving the .Net runtime has periods where it's 
busy doing its garbage collection and other housekeeping and the microphone samples
jump from a 20ms period up to a 100 or 200ms period. The softphone supplied audio
will still be usable at the remote end of the call but it will be jumpy and possibly
have clicks and static.

I've only implemented support for the PCMU (G711 ULAW) codec so if the remote SIP 
device doesn't support it a call will not be possible.
As far as audio devices go the default input and output devices are used and there
is no user interface option facility to change that. Can be done via code.

**Comment by sipsorcery** [comment]
> Are the following issues still valid on the library?

Mostly no. Audio performance is now better due to .NET improvements. If you are using the .NET Framework then the generated audio sources or playing samples from a file will often still be choppy. If you're using .NET Core then the audio should be fine.

> Isn't support for other codecs now allowed ?

Other then G711 (PCMU and PCMA) the only other codec I have integrated is G722. It's certainly possible to add additional codecs but so far I haven't and don't have any immediate plans to do so.
