### ISSUE TITLE
SIPSorcery.SIP.SIPTransport.Shutdown leaves connected sockets in WAIT state (v1.5.6)

### ISSUE THREAD

**Issue by grmihel2** [sipsorcery/sipsorcery#47]
When I have an established connection between endpoints, those will stay in a WAIT_TIME state on the related socket, when SIPTransport.Shutdown has been initiated.

**Log output:**
Starting logging initialisation.
137  [5] DEBUG sipsorcery (null) - Logging initialised.
318  [5] DEBUG sipsorcery.sip (null) - SIP TCP Channel listener created 1.1.1.1:47002.
335  [siptcp-47002] DEBUG sipsorcery.sip (null) - SIPTCPChannel socket on tcp:1.1.1.1:47002 accept connections thread started.
1104 [18] DEBUG sipsorcery.sip (null) - Attempting to establish TCP connection to 1.1.1.2:5060.
1117 [11] DEBUG sipsorcery.sip (null) - Established TCP connection to 1.1.1.2:5060.
41353 [18] DEBUG sipsorcery.sip (null) - Closing SIP TCP Channel tcp:1.1.1.1:47002.
41375 [siptcp-47002] WARN  sipsorcery.sip (null) - Exception SIPTCPChannel  accepting socket (System.Net.Sockets.SocketException). A blocking operation was interrupted by a call to WSACancelBlockingCall
41377 [20] WARN  sipsorcery.sip (null) - Exception SIPTCPChannel ReceiveCallback. Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.
41376 [siptransport-receive] WARN  sipsorcery.sip (null) - SIPTransport process received messsages thread stopped.
41376 [18] DEBUG sipsorcery.sip (null) - SIPTransport Shutdown Complete.
41397 [siptcp-47002] DEBUG sipsorcery.sip (null) - SIPTCPChannel socket on tcp:1.1.1.1:47002 listening halted.
41417 [20] DEBUG sipsorcery.sip (null) - TCP socket from 1.1.1.2:5060 disconnected.

Even tho the last line claims that TCP socket from 1.1.1.2:5060 has been disconnect, a netstat shows that this is not the case, or at least, that the connection is in a TIME_WAIT state, which should be avoided.

By looking at the SIPSorcery code, I cannot see why this happens, as the TcpListener is shut down first, followed by a TcpClient shutdown (SocketShutdown.Both).

**Comment by moerwald** [comment]
@grmihel2: I think this is ok. Read this [link](https://blogs.technet.microsoft.com/networking/2010/08/11/how-tcp-time-wait-assassination-works/) about explanation. 

Here is also an additional explanation from [stackoverflow](https://stackoverflow.com/questions/337115/setting-time-wait-tcp):

> The reason why there is a TIME_WAIT state following session shutdown is because there may still be 
> live packets out in the network on their way to you (or from you which may solicit a response of some 
> sort). If you were to re-create that same tuple and one of those packets showed up, it would be treated 
> as a valid packet for your connection (and probably cause an error due to sequencing).

Does the TCP connection remains in state "TIME_WAIT" forever? My guess is, that if netstat for the TCP port some seconds later the "TIME_WAIT" connection disappears.

**Comment by sipsorcery** [comment]
This behaviour was always a minor annoyance to me a well. While it is [correct behaviour for TCP](http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html) but it's not particularly suitable for SIP due to:

- SIP connections can have a valid reason to always be established to and from the exact same port. For example if a SIP Provider white lists a SIP server it will often be for port 5060 only. If the TCP connection is dropped for any reason the TIME_WAIT state could force a delay on allowing that connection to be re-established (on Windows the default TIME_WAIT delay is 30s),

- The SIP protocol has its own reliability mechanisms built in so that it can cope with the UDP transport. One of the purposes of TIME_WAIT is to avoid any stray TCP packets from being received after the connection is closed. SIP can easily handle such stray packets.

I have now gotten to the bottom of the issue and done a substantial refactor of the TCP and TLS channels. The TIME_WAIT state is now avoided. The cost is that TCP connections are forced to close with a hard RST rather than the graceful FIN-ACK. I don't anticipate this will have any side effects but there is a possibility that a network element such as a firewall or SIP border controller could take certain actions on RST packets. I think this is unlikely.

The output and image below shows the log messages and raw packets that now result when closing a SIP TCP channel:

````
[13:08:24 INF] => Got correct response on send 1 of 1 in 74ms.
[13:08:24 DBG] Shutting down the SIP transport...
[13:08:24 DBG] Closing SIP TCP Channel tcp:[::1]:9060.
[13:08:24 DBG] SIP stream disconnected tcp:[::1]:5060 OperationAborted.
[13:08:24 DBG] SIPTCPChannel accepts for tcp:[::1]:9060 cancelled.
[13:08:25 INF] => Command completed successfully.
````
![tcp_close](https://user-images.githubusercontent.com/197660/67619322-e0ab1c00-f7f1-11e9-9b0a-1eea09dd45b5.png)

On Windows the easiest way to identify TCP connection closes being stuck in a TIME_WAIT state is with `netsh`, for example:

````
netsh int ipv4 show tcpconnections localport=5060 rr=1
````
![netsh_timewait](https://user-images.githubusercontent.com/197660/67619343-4a2b2a80-f7f2-11e9-846b-a650f2c0f521.png)

The above condition will now NO longer occur with the sipsorcery TCP and TLS channels,
