### ISSUE TITLE
Play Audio File

### ISSUE THREAD

**Issue by joaodotneto** [sipsorcery/sipsorcery#66]
Hello fellas!
I want to play an audio file in the current call. I'm using the SoftPhone project as reference, and i try to put the "play function" in the RTPManager class, like that:
`public void PlayAudio(byte[] buffer)
{
        if (_rtpAudioChannel.RemoteEndPoint != null)
        {
		_rtpAudioChannel.SetFrameType(FrameTypesEnum.Audio);
		MemoryStream memoryStream = new MemoryStream(buffer);
		int bytesRead = 0;
		byte[] sample = new byte[160];
		bytesRead = memoryStream.Read(sample, 0, 160);
		while (bytesRead > 0)
		{
			_rtpAudioChannel.SendAudioFrame(sample, 160, (int)SDPMediaFormatsEnum.PCMU);
			bytesRead = memoryStream.Read(sample, 0, 160);
		}
	}
}`
This injects the buffer, but only i hear is dirty.
The file i try to play is attached.
[TesteAudioSip.zip](https://github.com/sipsorcery/sipsorcery/files/2821336/TesteAudioSip.zip)

**Comment by rj2Skipper** [comment]
Hi,
Disturbed Audio comes (in my experience) most times from wrong input.
did you make sure your audio file is really PCMU and that you have "negotiated" PCMU via SIP/SDP?
SipSorcery will not convert the your bytearrays to any negotiated format.

ciao Ralf

**Comment by joaodotneto** [comment]
> Hi,
> Disturbed Audio comes (in my experience) most times from wrong input.
> did you make sure your audio file is really PCMU and that you have "negotiated" PCMU via SIP/SDP?
> SipSorcery will not convert the your bytearrays to any negotiated format.
> 
> ciao Ralf

Thanks for the response. 
The example audio is attached, and the format are correct. 
As i said, i'm using the SoftPhone project, and the negotiated format is PCMU.
Do you have any example code and audio to help me?

**Comment by apdevelop** [comment]
What is the right approach for sending a long array of samples (which were read from file and converted to PCMU format) using `RTPChannel.SendAudioFrame` method? Especially `frameSpacing` argument value and pause duration between calling that method (if needed).

**Comment by sipsorcery** [comment]
Take a look at the [RTPSession class](https://github.com/sipsorcery/sipsorcery/blob/master/sipsorcery-core/SIPSorcery.Net/RTP/RTPSession.cs) and the SendAudioFrame method as an example.

The tricky but is, as you seem to have recognised, the timing. If the remote end is playing back the audio in near real-time then you need to attempt to deliver it as a constant stream, not too fast and not too slow. Jitter buffers and such will help but the timing still needs to be close to real-time.

If you're using the .Net framework on Windows then you're likely to be constrained to a minimum delay of 30ms. In my experience any time you sleep on a .Net thread that's the lowest you can go. That means you want to bundle up more than 30ms of audio in each RTP packet. A hardware IP Phone will typically use a payload size of [20 to 30ms ](https://www.cisco.com/c/en/us/support/docs/voice/voice-quality/7934-bwidth-consume.html) but trying to do that with C# in .Net is not feasible. I'd recommend starting at a payload size of 50ms and adjust as required.

**Comment by apdevelop** [comment]
Thank you for fast reply, another option can be _computing_ RTP packet timestamp offset (instead of using system timer) when sending data in real time from fixed source (media file). AFAIR, the `ffmpeg` can use such approach for generating stable RTP timestamps.
_(I'm trying to send correctly generated DTMF samples inside audio RTP channel)._

**Comment by sipsorcery** [comment]
No you don't want to do that. The timestamps set in each RTP packet need to be relative. For g711 the sampling rate is defined as 8000 samples per second and 8 bits per sample or to put it another way you need to transmit 64KB per second or audio. 

If you send 50ms of audio per packet your payload and timestamps would be:

packet 1: timestamp 0*, payload 0 to 3199
packet 2: timestamp 3200, payload 3200 to 6399
packet 3; timestamp 6400, payload 6400 to 9599
...
packet 20: timestamp 64000, payload 60800 to 63999

* you are meant to start RTP timestamps from a random offset but 0 always works.

Note that g711 is one of the simplest cases since you can increment the timestamp simply be using the size of the voice sample.

The task of synchronising the RTP relative timestamp to a wall clock (real time) is what RTCP sender reports are for. You can probably ignore them at this point unless you are attempting to synchronise multiple media streams such as a combined audio and video playback.

**Comment by apdevelop** [comment]
Now I'm testing audio file playback using two these approaches:

1.  `System.Threading.Timer` with 5ms period, then its callback method is calling `SampleReady` event several times, the number of calls is computed as `number = sessionElapsedMilliseconds / 20 - numberOfTransmittedPackets`, so the RTP packets are sent finally on rather regular basis.
It is used when no audio recording devices are used and audio data is generated or loaded from file.

2.  `AudioChannel.AudioSampleAvailable` callback, which is called on regular basis when next 20ms buffer is captured from input device, but these captured samples are discarded.

In both cases there is separate buffer (queue) with PCMU samples is prepared, and these samples are sending instead of captured ones. If this buffer is empty, the zero values (silence) is passed to `SampleReady` .

_P.S. I know, that soft realtime on Windows + .NET is rather hard thing :)_

**Comment by sipsorcery** [comment]
I think this issue is resolved but if it helps anyone else the recently added [UserAgentServer](https://github.com/sipsorcery/sipsorcery/blob/master/examples/UserAgentServer/Program.cs) example program generates an RTP stream from either a `.ulaw` or `.mp3` file.

The audio is choppy when running on Windows due to the .NET framework having poor determinism for sub 50ms intervals.

**Comment by bergqvm** [comment]
Hi,
I had some issues with the AudioExtrasSource giving unreliable timing due to the use of the Timer class giving non reliable timing. Appears to be a problem in larger .NET applications with multiple threads.
I have replaced the _sendSampleTimer with the MicroTimer from  https://www.codeproject.com/Articles/98346/Microsecond-and-Millisecond-NET-Timer and the issues have now gone away in generating the audio packets no dropouts.

BR
Mikael

**Comment by franck-malka** [comment]
Hey Mikael,

Can you shared the modified AudioExtrasSource class?

-Franck.

**Comment by bergqvm** [comment]
@franck-malka I made an example in #404

**Comment by franck-malka** [comment]
Thanks, but this timer is consuming way too much cpu for multi channels

**Comment by bergqvm** [comment]
@franck-malka  There is some suggestions in the code project discussion thread about reducing the CPU overhead of the timer. I have not tested it but it may be of interest to you.
https://www.codeproject.com/Messages/5288003/To-reduce-CPU-usage
