### ISSUE TITLE
Please provide a working build for SIPSorceryMedia.sln

### ISSUE THREAD

**Issue by bleissem** [sipsorcery/sipsorcery#72]
When I clone 
https://github.com/sipsorcery/sipsorcery
and try to build
sipsorcery\sipsorcery-media\SIPSorcery.Media\SIPSorceryMedia.sln
it won't build 
Unfortunately the 
https://ci.appveyor.com/project/sipsorcery/sipsorcery
build does not seem to build this solution either.
So please provide a working build for SIPSorceryMedia.sln or a SIPSorceryMedia.sln that can be builded.
Thanks in advance

**Comment by sipsorcery** [comment]
As you can see that library isn't actively maintained. It was predominantly written for prototyping and never made it into the production service I run.

That being said [vcpkg](https://github.com/microsoft/vcpkg) has come along since this library was written and makes build way way easier. I've done a quick bit of messing around and made progress after installing these dependencies:

````
c:\Tools\vcpkg>vcpkg install openssl:x64-windows
c:\Tools\vcpkg>vcpkg install libvpx:x64-windows
c:\Tools\vcpkg>vcpkg install ffmpeg:x64-windows
````

I still get a winsock error afterwards, looks like there's two different versions in use somewhere. I'll attempt to resolve it as time permits but it may not be in a hurry...

**Comment by sipsorcery** [comment]
I've pushed a commit that should get the SIPSorceryMedia solution building.
