### ISSUE TITLE
UserAgentServer sample: no audio, or unsupported codec error

### ISSUE THREAD

**Issue by roy-t** [sipsorcery/sipsorcery#95]
I'm using the latest UserAgentServer example from master, unmodified. It runs fine and I can connect to it using multiple softphone applications. I see negotiation is going well and that the RTP stream is set-up.

![image](https://user-images.githubusercontent.com/623634/68894090-d57b4a00-0726-11ea-8c46-729a14b4ad07.png)

In wireshark I've verified which audio codec is used:

![image](https://user-images.githubusercontent.com/623634/68893788-26d70980-0726-11ea-9c65-6675a56c8592.png)

In MicroSIP the audio stream says silent. In Zoiper I get an error that the audio codec is not supported. In both applications I've enabled all audio codecs, and both applications support both G.711 a-law and G.711 u-law and many other codecs. I can hear audio fine in both applications when connecting to other servers.

I've played a bit with the code to use the mp3 file instead of the ulaw file. I even tried outputting the raw PCM stream. But still I don't hear anything. What further can I do to debug this issue?

**Comment by sipsorcery** [comment]
The `UserAgentServer` example only supports `PCMU`. If you take a look in the `GetSDP` method you'll see that's the only media type offered but apart from that it's also the only one audio format that `SendRecvRtp` can supply.

Other than that your console log looks correct. If you've got Wireshark up and running it's the easiest way to see if the problem is the audio not getting sent or if it's the receiving device not happy with it.

In Wireshark click on `Telephony->RTP->RTP Streams` and 

![cap1](https://user-images.githubusercontent.com/197660/68896409-52a4c000-0723-11ea-8f27-c8b4179c99b1.png)

Then highlight the desired stream (in this case there should only be one) and click `Analyze`. You should get a screen like the one below:

![cap2](https://user-images.githubusercontent.com/197660/68896381-41f44a00-0723-11ea-9532-81bad591d5fe.png)

The click `Play Streams` to get the screen below and the click the `Play` button and if all goes well you should hear the music.

![cap3](https://user-images.githubusercontent.com/197660/68896539-98fa1f00-0723-11ea-8266-a458abfa0232.png)

I did a test with the Xten softphone and it worked correctly for me. Another test you can do is to use the `UserAgentClient` example program. The steps are:

1. Start the server with: `sipsorcery-core\examples\UserAgentServer>dotnet run`
2. Start the client with: `sipsorcery-core\examples\UserAgentClient>dotnet run -- 127.0.0.1`

If it works you should hear the music almost immediately.

![uas_and uac](https://user-images.githubusercontent.com/197660/68896917-5b49c600-0724-11ea-879c-2f1d04329448.png)

**Comment by roy-t** [comment]
Thank you for the extremely detailed response. I've verified in wireshark that the audiostream is working, and in wireshark I can hear the audio.  MicroSip explicitly supports  PCMU (G711u). I've verified that I have it enabled, and if I disable the codec it will complain during connection that the server is sending an unsupported codec. But unfortunately I still don't get audio.

I also tried Xten, but unfortunately I can't get it to dial/make a connection. I've entered all the server settings. But it just wont do anything when I press the dial button. It might be I just don't understand the UI. But even the diagnostic logs don't show much.

I then tried the UserAgentClient. But it seems I'm having an unlucky day. The client wont connect to the server at all:
![image](https://user-images.githubusercontent.com/623634/68902360-61e23880-0738-11ea-8fa0-a085c2a6a497.png)

As said before I'm on the latest commit on master (51591beef3fb4df2187c842fecd5b422d66f74e7, from today).

**Comment by roy-t** [comment]
I think I figured out part of the problem. If I look in your console log the RTP stream is sent 127.0.0.1. But in my logs the RTP stream log line shows 
`0.0.0.0:49002->192.168.1.36:4000`. 
192.168.1.36 is this computer's internal IP address. But it might be that my router/firewall blocks the RTP stream.

The weird thing is that the SIP part is talking to 127.0.0.1 as you can see from this log line:
`Incoming call request: udp:0.0.0.0:5060<-udp:127.0.0.1:59454`

I'll see if I can hardcode localhost in the sample this weekend, or if I can tweak my firewall/router.

**Comment by sipsorcery** [comment]
The problem was related to the use of `IPAddress.Any` (or `0.0.0.0`). Turns out SIP softphones handle it differently and that most don't like it at all.

I've added a new command line option to the `UserAgentServer` example so that the IP address it uses can be specified:

`dotnet run -- 192.168.1.36`

Doing that got MicroSip and Zoiper working for me.

**Comment by roy-t** [comment]
Now it works great! Thanks so much for the research, explanation and quick fix!
